"""Canonical Company Intelligence contracts and compatibility adapters."""

from dealix.company_intelligence.action_adapter import normalize_next_best_action
from dealix.company_intelligence.action_contracts import (
    ActionStatus,
    ActionType,
    AutonomyLevel,
    CanonicalAction,
    RiskLevel,
    build_action,
    compute_priority_score,
    is_valid_transition,
    transition_action,
    valid_transitions_from,
)
from dealix.company_intelligence.adapter_registry import (
    AdapterEntry,
    AdapterStatus,
    get_active_adapters,
    get_adapter_entry,
    get_adapter_registry,
    get_all_normalize_functions,
    validate_coverage,
)
from dealix.company_intelligence.communication_contracts import (
    CanonicalCommunicationStyle,
    CommunicationLanguage,
    CommunicationStyleStatus,
    CommunicationTone,
    CulturalContext,
    ResponseLength,
    build_communication_style,
    is_valid_style_transition,
    transition_style,
    valid_style_transitions_from,
)
from dealix.company_intelligence.company_brain import (
    CanonicalCompanyBrain,
    build_customer_company_brain,
    build_internal_company_brain,
)
from dealix.company_intelligence.consent_adapter import normalize_consent
from dealix.company_intelligence.consent_contracts import (
    CanonicalConsentBasis,
    ConsentBasisStatus,
    ConsentBasisType,
    ConsentChannel,
    build_consent_basis,
    is_consent_expired,
    is_valid_consent_transition,
    transition_consent_basis,
    valid_consent_transitions_from,
)
from dealix.company_intelligence.contracts import CompanyBrainSource, ProvenanceRef
from dealix.company_intelligence.department_contracts import (
    CanonicalDepartmentPlan,
    Department,
    PlanPriority,
    PlanStatus,
    build_department_plan,
    is_valid_plan_transition,
    transition_plan,
    valid_plan_transitions_from,
)
from dealix.company_intelligence.execution_contracts import (
    CanonicalApproval,
    CanonicalApprovalStatus,
    CanonicalDraft,
    CanonicalOpportunity,
    DraftChannel,
    DraftStatus,
    LawfulContactBasis,
    OpportunityStage,
    build_draft,
    is_valid_approval_transition,
    is_valid_draft_transition,
    is_valid_opportunity_transition,
    normalize_approval,
    normalize_draft,
    normalize_opportunity,
    transition_approval,
    transition_draft,
    transition_opportunity,
    valid_approval_transitions_from,
    valid_draft_transitions_from,
    valid_opportunity_transitions_from,
)
from dealix.company_intelligence.graph_adapter import (
    normalize_lead_to_company,
    normalize_lead_to_contact,
)
from dealix.company_intelligence.graph_contracts import (
    CanonicalCompany,
    CanonicalContact,
    CompanyStatus,
    ContactRole,
    ContactStatus,
    RelationshipStrength,
    build_company,
    build_contact,
    is_valid_company_transition,
    is_valid_contact_transition,
    transition_company,
    transition_contact,
    valid_company_transitions_from,
    valid_contact_transitions_from,
)
from dealix.company_intelligence.human_loop_contracts import (
    CanonicalHumanLoopPolicy,
    EscalationRule,
    EscalationTrigger,
    HumanLoopMode,
    HumanLoopPolicyStatus,
    TimeoutAction,
    build_human_loop_policy,
    is_valid_policy_transition,
    requires_human_approval,
    transition_policy,
    valid_policy_transitions_from,
)
from dealix.company_intelligence.learning_adapter import (
    normalize_learning_event,
    normalize_win_loss,
)
from dealix.company_intelligence.negotiation_contracts import (
    CanonicalNegotiationStrategy,
    NegotiationApproach,
    NegotiationBoundary,
    NegotiationBoundaryType,
    NegotiationStage,
    NegotiationStrategyStatus,
    build_negotiation_strategy,
    is_valid_negotiation_stage_transition,
    is_valid_strategy_transition,
    transition_negotiation_stage,
    transition_negotiation_status,
    valid_negotiation_stage_transitions_from,
    valid_strategy_transitions_from,
)
from dealix.company_intelligence.offer_adapter import (
    normalize_catalog,
    normalize_service_offering,
)
from dealix.company_intelligence.offer_contracts import (
    CanonicalOffer,
    OfferApprovalPolicy,
    OfferPriceUnit,
    OfferStatus,
    build_offer,
)
from dealix.company_intelligence.partnership_contracts import (
    CanonicalPartnershipOpportunity,
    PartnershipStage,
    PartnershipType,
    build_partnership_opportunity,
    is_valid_partnership_transition,
    transition_partnership,
    valid_partnership_transitions_from,
)
from dealix.company_intelligence.persona_contracts import (
    CanonicalPersona,
    PersonaStatus,
    build_persona,
    is_valid_persona_transition,
    transition_persona,
    valid_persona_transitions_from,
)
from dealix.company_intelligence.pipeline_adapter import normalize_pipeline_lead
from dealix.company_intelligence.playbook_adapter import normalize_sector_playbook
from dealix.company_intelligence.playbook_contracts import (
    CanonicalPlaybookVersion,
    PlaybookApprovalStatus,
    build_playbook_version,
    is_valid_playbook_transition,
    transition_playbook,
    valid_playbook_transitions_from,
)
from dealix.company_intelligence.proof_adapter import normalize_proof_event
from dealix.company_intelligence.proposal_adapter import normalize_proposal
from dealix.company_intelligence.proposal_contracts import (
    CanonicalProposal,
    ProposalStatus,
    build_proposal,
    is_valid_proposal_transition,
    transition_proposal,
    valid_proposal_transitions_from,
)
from dealix.company_intelligence.relationship_contracts import (
    CanonicalRelationship,
    EntityType,
    RelationshipStatus,
    RelationshipType,
    build_relationship,
    is_valid_relationship_transition,
    transition_relationship,
    valid_relationship_transitions_from,
)
from dealix.company_intelligence.revenue_graph_adapter import (
    is_relationship_edge,
    normalize_graph_edge,
)
from dealix.company_intelligence.signal_adapter import normalize_signal
from dealix.company_intelligence.signal_contracts import (
    CanonicalSignal,
    ConsentStatus,
    SignalSensitivity,
    SignalStatus,
    SignalType,
    build_signal,
    is_signal_stale,
    is_valid_signal_transition,
    transition_signal,
    valid_signal_transitions_from,
)
from dealix.company_intelligence.source_adapter import normalize_source_passport
from dealix.company_intelligence.source_contracts import (
    CanonicalSource,
    SourcePolicyStatus,
    SourceStatus,
    SourceType,
    build_source,
    compute_source_score,
    is_source_stale,
    is_valid_source_transition,
    transition_source,
    valid_source_transitions_from,
)
from dealix.company_intelligence.tenant_contracts import (
    CanonicalTenant,
    TenantPlan,
    TenantStatus,
    build_tenant,
    is_valid_tenant_transition,
    transition_tenant,
    valid_tenant_transitions_from,
)

from . import outcome_contracts as _outcome_contracts

CanonicalDailyCommand = _outcome_contracts.CanonicalDailyCommand
CanonicalLearningEvent = _outcome_contracts.CanonicalLearningEvent
CanonicalOutcomeEvent = _outcome_contracts.CanonicalOutcomeEvent
CanonicalProofEvent = _outcome_contracts.CanonicalProofEvent
EvidenceState = _outcome_contracts.EvidenceState
LearningEventType = _outcome_contracts.LearningEventType
OutcomeEventType = _outcome_contracts.OutcomeEventType
ProofSourceEventType = _outcome_contracts.ProofSourceEventType
ProofType = _outcome_contracts.ProofType
build_daily_command = _outcome_contracts.build_daily_command
build_learning_event = _outcome_contracts.build_learning_event
build_outcome_event = _outcome_contracts.build_outcome_event
build_proof_event = _outcome_contracts.build_proof_event

# Preserve the legacy direct-import path while routing it to the fail-closed
# compatibility adapter. The module is loaded once above, so this does not
# create a competing implementation or import path.
_outcome_contracts.normalize_proof_event = normalize_proof_event

__all__ = [
    "AdapterEntry",
    "AdapterStatus",
    "ActionStatus",
    "CanonicalCommunicationStyle",
    "CanonicalHumanLoopPolicy",
    "CanonicalNegotiationStrategy",
    "CommunicationLanguage",
    "CommunicationStyleStatus",
    "CommunicationTone",
    "CulturalContext",
    "EscalationRule",
    "EscalationTrigger",
    "HumanLoopMode",
    "HumanLoopPolicyStatus",
    "NegotiationApproach",
    "NegotiationBoundary",
    "NegotiationBoundaryType",
    "NegotiationStage",
    "NegotiationStrategyStatus",
    "ResponseLength",
    "TimeoutAction",
    "ActionType",
    "AutonomyLevel",
    "CanonicalAction",
    "CanonicalApproval",
    "CanonicalApprovalStatus",
    "CanonicalCompany",
    "CanonicalCompanyBrain",
    "CanonicalConsentBasis",
    "CanonicalContact",
    "CanonicalDailyCommand",
    "CanonicalDepartmentPlan",
    "CanonicalDraft",
    "CanonicalLearningEvent",
    "CanonicalOffer",
    "CanonicalOpportunity",
    "CanonicalOutcomeEvent",
    "CanonicalPartnershipOpportunity",
    "CanonicalPersona",
    "CanonicalPlaybookVersion",
    "CanonicalProofEvent",
    "CanonicalProposal",
    "CanonicalRelationship",
    "CanonicalSignal",
    "CanonicalSource",
    "CanonicalTenant",
    "CompanyBrainSource",
    "CompanyStatus",
    "ConsentBasisStatus",
    "ConsentBasisType",
    "ConsentChannel",
    "ConsentStatus",
    "ContactRole",
    "ContactStatus",
    "Department",
    "DraftChannel",
    "DraftStatus",
    "EntityType",
    "EvidenceState",
    "LawfulContactBasis",
    "LearningEventType",
    "OfferApprovalPolicy",
    "OfferPriceUnit",
    "OfferStatus",
    "OpportunityStage",
    "OutcomeEventType",
    "PartnershipStage",
    "PartnershipType",
    "PersonaStatus",
    "PlaybookApprovalStatus",
    "PlanPriority",
    "PlanStatus",
    "ProofSourceEventType",
    "ProofType",
    "ProposalStatus",
    "ProvenanceRef",
    "RelationshipStatus",
    "RelationshipStrength",
    "RelationshipType",
    "RiskLevel",
    "SignalSensitivity",
    "SignalStatus",
    "SignalType",
    "SourcePolicyStatus",
    "SourceStatus",
    "SourceType",
    "TenantPlan",
    "TenantStatus",
    "build_action",
    "build_communication_style",
    "build_company",
    "build_consent_basis",
    "build_contact",
    "build_customer_company_brain",
    "build_daily_command",
    "build_department_plan",
    "build_draft",
    "build_human_loop_policy",
    "build_internal_company_brain",
    "build_learning_event",
    "build_negotiation_strategy",
    "build_offer",
    "build_outcome_event",
    "build_partnership_opportunity",
    "build_persona",
    "build_playbook_version",
    "build_proof_event",
    "build_proposal",
    "build_relationship",
    "build_signal",
    "build_source",
    "build_tenant",
    "compute_priority_score",
    "compute_source_score",
    "get_active_adapters",
    "get_adapter_entry",
    "get_adapter_registry",
    "get_all_normalize_functions",
    "is_consent_expired",
    "is_signal_stale",
    "is_source_stale",
    "is_valid_approval_transition",
    "is_valid_negotiation_stage_transition",
    "is_valid_policy_transition",
    "is_valid_strategy_transition",
    "is_valid_style_transition",
    "is_valid_company_transition",
    "is_valid_consent_transition",
    "is_valid_contact_transition",
    "is_valid_draft_transition",
    "is_valid_opportunity_transition",
    "is_valid_partnership_transition",
    "is_valid_persona_transition",
    "is_valid_plan_transition",
    "is_valid_playbook_transition",
    "is_valid_proposal_transition",
    "is_valid_relationship_transition",
    "is_valid_signal_transition",
    "is_valid_source_transition",
    "is_valid_tenant_transition",
    "is_valid_transition",
    "is_relationship_edge",
    "normalize_approval",
    "normalize_catalog",
    "normalize_consent",
    "normalize_draft",
    "normalize_graph_edge",
    "normalize_lead_to_company",
    "normalize_lead_to_contact",
    "normalize_learning_event",
    "normalize_next_best_action",
    "normalize_opportunity",
    "normalize_pipeline_lead",
    "normalize_proof_event",
    "normalize_proposal",
    "normalize_sector_playbook",
    "normalize_service_offering",
    "normalize_signal",
    "normalize_source_passport",
    "normalize_win_loss",
    "requires_human_approval",
    "transition_action",
    "transition_approval",
    "transition_company",
    "transition_consent_basis",
    "transition_contact",
    "transition_draft",
    "transition_negotiation_stage",
    "transition_negotiation_status",
    "transition_opportunity",
    "transition_partnership",
    "transition_persona",
    "transition_plan",
    "transition_playbook",
    "transition_policy",
    "transition_proposal",
    "transition_relationship",
    "transition_signal",
    "transition_source",
    "transition_style",
    "transition_tenant",
    "valid_approval_transitions_from",
    "valid_negotiation_stage_transitions_from",
    "valid_policy_transitions_from",
    "valid_strategy_transitions_from",
    "valid_style_transitions_from",
    "valid_company_transitions_from",
    "valid_consent_transitions_from",
    "valid_contact_transitions_from",
    "valid_draft_transitions_from",
    "valid_opportunity_transitions_from",
    "valid_partnership_transitions_from",
    "valid_persona_transitions_from",
    "valid_plan_transitions_from",
    "valid_playbook_transitions_from",
    "valid_proposal_transitions_from",
    "valid_relationship_transitions_from",
    "valid_signal_transitions_from",
    "valid_source_transitions_from",
    "valid_tenant_transitions_from",
    "valid_transitions_from",
    "validate_coverage",
]
