"""Negotiation Intelligence Engine for Company Intelligence.

Provides tactical intelligence for deal negotiation: assessing positions,
recommending moves, evaluating counter-offers, and tracking concessions.
Uses NegotiationStrategy contracts to enforce boundaries and approach.

This engine NEVER makes commitments. It produces assessments and
recommendations that flow through the Action → Approval chain.
All pricing/scope commitments require human approval.

The engine is persistence-neutral: no database, network, or LLM calls.

Entity ownership:
    Uses NegotiationStrategy (deal_intelligence) contracts.
    Produces inputs for Action (action_queue) and Draft (draft_generation).
"""
from __future__ import annotations

import json
from datetime import UTC, datetime
from enum import StrEnum
from hashlib import sha256
from typing import Annotated, Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    model_validator,
)

from dealix.company_intelligence.negotiation_contracts import (
    CanonicalNegotiationStrategy,
    NegotiationBoundary,
    NegotiationBoundaryType,
    NegotiationStage,
)

NonEmptyString = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1)]


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class MoveType(StrEnum):
    """Types of tactical moves in a negotiation."""

    ANCHOR = "anchor"
    CONCEDE = "concede"
    HOLD_FIRM = "hold_firm"
    COUNTER = "counter"
    REFRAME = "reframe"
    ADD_VALUE = "add_value"
    ESCALATE = "escalate"
    CLOSE = "close"
    WALK_AWAY = "walk_away"
    PAUSE = "pause"


class BoundaryStatus(StrEnum):
    """Result of checking a position against strategy boundaries."""

    WITHIN = "within"
    SOFT_WARNING = "soft_warning"
    HARD_VIOLATION = "hard_violation"


class PositionStrength(StrEnum):
    """Relative strength of the negotiation position."""

    STRONG = "strong"
    MODERATE = "moderate"
    WEAK = "weak"
    CRITICAL = "critical"


# ---------------------------------------------------------------------------
# Stable IDs
# ---------------------------------------------------------------------------


def _stable_assessment_id(payload: dict[str, Any]) -> str:
    canonical = json.dumps(
        payload,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
        default=str,
    )
    return f"negassess_{sha256(canonical.encode('utf-8')).hexdigest()[:16]}"


def _stable_move_id(payload: dict[str, Any]) -> str:
    canonical = json.dumps(
        payload,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
        default=str,
    )
    return f"negmove_{sha256(canonical.encode('utf-8')).hexdigest()[:16]}"


# ---------------------------------------------------------------------------
# Boundary Check Result
# ---------------------------------------------------------------------------


class BoundaryCheckResult(BaseModel):
    """Result of checking a value against a negotiation boundary.

    Captures which boundary was checked, whether it was violated, and
    whether the violation is a hard stop or a soft warning.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    boundary: NegotiationBoundary
    status: BoundaryStatus
    current_value: str = ""
    message: str = ""


# ---------------------------------------------------------------------------
# Negotiation Assessment — snapshot of position
# ---------------------------------------------------------------------------


class NegotiationAssessment(BaseModel):
    """A point-in-time assessment of a negotiation's position.

    Assessments are generated by the Negotiation Engine to help the
    human approver understand the current state of a deal and make
    informed decisions.

    Key invariants:
        - assessment_id is deterministic.
        - requires_human_decision is always True for recommendations
          involving commitments.
        - boundary_violations trigger automatic escalation.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    # Identity
    tenant_id: NonEmptyString
    assessment_id: NonEmptyString
    strategy_id: NonEmptyString
    opportunity_id: NonEmptyString

    # Position analysis
    current_stage: NegotiationStage
    position_strength: PositionStrength
    win_probability: float = Field(default=0.0, ge=0.0, le=1.0)

    # Boundary status
    boundary_checks: tuple[BoundaryCheckResult, ...] = ()
    has_hard_violations: bool = False
    has_soft_warnings: bool = False

    # Concession tracking
    concessions_made: tuple[str, ...] = ()
    concessions_remaining: tuple[str, ...] = ()
    total_concession_value_pct: float = Field(default=0.0, ge=0.0, le=1.0)

    # Scoring
    leverage_score: float = Field(default=0.5, ge=0.0, le=1.0)
    urgency_score: float = Field(default=0.5, ge=0.0, le=1.0)

    # Decision support
    key_risks: tuple[str, ...] = ()
    key_advantages: tuple[str, ...] = ()
    requires_human_decision: bool = True

    # Provenance
    source_id: NonEmptyString
    assessed_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @model_validator(mode="after")
    def enforce_assessment_invariants(self) -> NegotiationAssessment:
        # Hard violations must be flagged
        hard_checks = [
            c for c in self.boundary_checks
            if c.status == BoundaryStatus.HARD_VIOLATION
        ]
        if hard_checks and not self.has_hard_violations:
            raise ValueError(
                "assessment has hard boundary violations but "
                "has_hard_violations is False"
            )

        # Soft warnings must be flagged
        soft_checks = [
            c for c in self.boundary_checks
            if c.status == BoundaryStatus.SOFT_WARNING
        ]
        if soft_checks and not self.has_soft_warnings:
            raise ValueError(
                "assessment has soft boundary warnings but "
                "has_soft_warnings is False"
            )

        # Verify deterministic ID
        expected_id = _stable_assessment_id({
            "opportunity_id": self.opportunity_id,
            "strategy_id": self.strategy_id,
            "tenant_id": self.tenant_id,
        })
        if self.assessment_id != expected_id:
            raise ValueError(
                "assessment_id does not match the canonical payload"
            )

        return self


# ---------------------------------------------------------------------------
# Recommended Move — what to do next
# ---------------------------------------------------------------------------


class RecommendedMove(BaseModel):
    """A tactical recommendation for the next negotiation action.

    RecommendedMoves are suggestions — never commitments. They require
    human approval before any external action is taken.

    Key invariants:
        - approval_required is always True.
        - execution_allowed is always False.
        - move_id is deterministic.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    # Identity
    tenant_id: NonEmptyString
    move_id: NonEmptyString
    assessment_id: NonEmptyString
    strategy_id: NonEmptyString

    # Move details
    move_type: MoveType
    description: NonEmptyString
    rationale: NonEmptyString

    # Talking points
    talking_points: tuple[str, ...] = ()
    objection_responses: tuple[tuple[str, str], ...] = ()

    # Value framing
    value_proposition: str = ""
    concession_offered: str = ""
    concession_requested: str = ""

    # Risk assessment
    risk_if_taken: str = ""
    risk_if_not_taken: str = ""
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)

    # Safety — ALWAYS
    approval_required: bool = True
    execution_allowed: bool = False

    # Provenance
    source_id: NonEmptyString
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))

    @model_validator(mode="after")
    def enforce_move_invariants(self) -> RecommendedMove:
        if not self.approval_required:
            raise ValueError(
                "recommended moves always require approval"
            )
        if self.execution_allowed:
            raise ValueError(
                "recommended moves never authorize execution"
            )

        expected_id = _stable_move_id({
            "assessment_id": self.assessment_id,
            "move_type": self.move_type.value,
            "strategy_id": self.strategy_id,
            "tenant_id": self.tenant_id,
        })
        if self.move_id != expected_id:
            raise ValueError(
                "move_id does not match the canonical payload"
            )

        return self


# ---------------------------------------------------------------------------
# Engine functions
# ---------------------------------------------------------------------------


def check_boundaries(
    strategy: CanonicalNegotiationStrategy,
    *,
    current_values: dict[str, str],
) -> list[BoundaryCheckResult]:
    """Check current negotiation values against strategy boundaries.

    Returns a list of BoundaryCheckResult for each boundary defined
    in the strategy. Missing values are treated as unknown (WITHIN).
    """
    results: list[BoundaryCheckResult] = []

    for boundary in strategy.boundaries:
        current = current_values.get(boundary.boundary_type.value, "")

        if not current:
            results.append(BoundaryCheckResult(
                boundary=boundary,
                status=BoundaryStatus.WITHIN,
                current_value="unknown",
                message=f"no value provided for {boundary.boundary_type.value}",
            ))
            continue

        # For numeric boundaries, try comparison
        try:
            current_num = float(current)
            boundary_num = float(boundary.value)

            if boundary.boundary_type == NegotiationBoundaryType.PRICE_FLOOR:
                if current_num < boundary_num:
                    status = (
                        BoundaryStatus.HARD_VIOLATION
                        if boundary.is_hard_limit
                        else BoundaryStatus.SOFT_WARNING
                    )
                    results.append(BoundaryCheckResult(
                        boundary=boundary,
                        status=status,
                        current_value=current,
                        message=(
                            f"price {current} is below floor {boundary.value}"
                        ),
                    ))
                    continue

            elif boundary.boundary_type == NegotiationBoundaryType.DISCOUNT_CEILING:
                if current_num > boundary_num:
                    status = (
                        BoundaryStatus.HARD_VIOLATION
                        if boundary.is_hard_limit
                        else BoundaryStatus.SOFT_WARNING
                    )
                    results.append(BoundaryCheckResult(
                        boundary=boundary,
                        status=status,
                        current_value=current,
                        message=(
                            f"discount {current} exceeds ceiling {boundary.value}"
                        ),
                    ))
                    continue

            elif boundary.boundary_type == NegotiationBoundaryType.TIMELINE_MINIMUM:
                if current_num < boundary_num:
                    status = (
                        BoundaryStatus.HARD_VIOLATION
                        if boundary.is_hard_limit
                        else BoundaryStatus.SOFT_WARNING
                    )
                    results.append(BoundaryCheckResult(
                        boundary=boundary,
                        status=status,
                        current_value=current,
                        message=(
                            f"timeline {current} is below minimum {boundary.value}"
                        ),
                    ))
                    continue

        except ValueError:
            pass  # Non-numeric — fall through to default

        # Default: within bounds
        results.append(BoundaryCheckResult(
            boundary=boundary,
            status=BoundaryStatus.WITHIN,
            current_value=current,
            message="within acceptable range",
        ))

    return results


def assess_position(
    strategy: CanonicalNegotiationStrategy,
    *,
    source_id: str,
    current_values: dict[str, str] | None = None,
    concessions_made: tuple[str, ...] = (),
    leverage_score: float = 0.5,
    urgency_score: float = 0.5,
    key_risks: tuple[str, ...] = (),
    key_advantages: tuple[str, ...] = (),
) -> NegotiationAssessment:
    """Assess the current negotiation position against strategy boundaries.

    Produces a NegotiationAssessment with boundary checks, position
    strength analysis, and decision-support context.
    """
    # Check boundaries
    boundary_checks = tuple(check_boundaries(
        strategy,
        current_values=current_values or {},
    ))

    has_hard = any(
        c.status == BoundaryStatus.HARD_VIOLATION for c in boundary_checks
    )
    has_soft = any(
        c.status == BoundaryStatus.SOFT_WARNING for c in boundary_checks
    )

    # Calculate remaining concessions
    made_set = set(concessions_made)
    remaining = tuple(
        c for c in strategy.concession_sequence if c not in made_set
    )
    total_concession_pct = (
        len(concessions_made) / max(len(strategy.concession_sequence), 1)
    )

    # Determine position strength
    if has_hard:
        strength = PositionStrength.CRITICAL
    elif has_soft or total_concession_pct > 0.7:
        strength = PositionStrength.WEAK
    elif leverage_score >= 0.6:
        strength = PositionStrength.STRONG
    else:
        strength = PositionStrength.MODERATE

    # Build assessment ID
    assessment_id = _stable_assessment_id({
        "opportunity_id": strategy.opportunity_id,
        "strategy_id": strategy.strategy_id,
        "tenant_id": strategy.tenant_id,
    })

    return NegotiationAssessment(
        tenant_id=strategy.tenant_id,
        assessment_id=assessment_id,
        strategy_id=strategy.strategy_id,
        opportunity_id=strategy.opportunity_id,
        current_stage=strategy.stage,
        position_strength=strength,
        win_probability=strategy.win_probability,
        boundary_checks=boundary_checks,
        has_hard_violations=has_hard,
        has_soft_warnings=has_soft,
        concessions_made=concessions_made,
        concessions_remaining=remaining,
        total_concession_value_pct=round(total_concession_pct, 2),
        leverage_score=leverage_score,
        urgency_score=urgency_score,
        key_risks=key_risks,
        key_advantages=key_advantages,
        requires_human_decision=True,
        source_id=source_id,
    )


def recommend_move(
    assessment: NegotiationAssessment,
    strategy: CanonicalNegotiationStrategy,
    *,
    source_id: str,
) -> RecommendedMove:
    """Recommend the next negotiation move based on assessment and strategy.

    The recommendation considers position strength, boundary status,
    remaining concessions, and the strategy's approach. It NEVER
    authorizes execution — only suggests.
    """
    # Determine move type based on position and stage
    if assessment.has_hard_violations:
        move_type = MoveType.WALK_AWAY
        description = "Hard boundary violation detected — recommend walking away"
        rationale = (
            "The current position violates a non-negotiable boundary. "
            "Continuing would compromise the deal structure."
        )
    elif assessment.position_strength == PositionStrength.CRITICAL:
        move_type = MoveType.ESCALATE
        description = "Critical position — escalate to senior decision maker"
        rationale = (
            "Position is critical with multiple risk factors. "
            "Escalation ensures proper decision authority."
        )
    elif strategy.stage == NegotiationStage.DISCOVERY:
        move_type = MoveType.ANCHOR
        description = "Anchor the discussion with value proposition"
        rationale = (
            "In discovery phase — establish value before discussing price. "
            "Lead with the strongest value anchors."
        )
    elif strategy.stage == NegotiationStage.POSITIONING:
        move_type = MoveType.REFRAME
        description = "Reframe around value rather than price"
        rationale = (
            "Positioning phase — shift conversation from cost to ROI "
            "and measurable outcomes."
        )
    elif strategy.stage in (NegotiationStage.COUNTER, NegotiationStage.STALEMATE):
        if len(assessment.concessions_remaining) > 0:
            move_type = MoveType.CONCEDE
            description = (
                f"Strategic concession: {assessment.concessions_remaining[0]}"
            )
            rationale = (
                f"Offer next planned concession to maintain momentum. "
                f"{len(assessment.concessions_remaining)} concessions remaining."
            )
        else:
            move_type = MoveType.HOLD_FIRM
            description = "Hold current position — no concessions remaining"
            rationale = (
                "All planned concessions exhausted. Hold firm or "
                "prepare alternative value additions."
            )
    elif strategy.stage == NegotiationStage.CLOSING:
        move_type = MoveType.CLOSE
        description = "Move to close — summarize agreed terms"
        rationale = (
            "Deal is in closing stage. Summarize agreements, confirm "
            "deliverables, and prepare final documentation."
        )
    elif assessment.position_strength == PositionStrength.STRONG:
        move_type = MoveType.ADD_VALUE
        description = "Add value to strengthen the proposal"
        rationale = (
            "Strong position — leverage it by adding value rather than "
            "lowering price. Demonstrate capability depth."
        )
    else:
        move_type = MoveType.COUNTER
        description = "Prepare a structured counter-proposal"
        rationale = (
            "Standard negotiation progression — prepare a counter "
            "addressing the other party's key concerns."
        )

    # Select relevant talking points from strategy
    talking_points = strategy.value_anchors[:5]

    # Build move ID
    move_id = _stable_move_id({
        "assessment_id": assessment.assessment_id,
        "move_type": move_type.value,
        "strategy_id": strategy.strategy_id,
        "tenant_id": strategy.tenant_id,
    })

    return RecommendedMove(
        tenant_id=strategy.tenant_id,
        move_id=move_id,
        assessment_id=assessment.assessment_id,
        strategy_id=strategy.strategy_id,
        move_type=move_type,
        description=description,
        rationale=rationale,
        talking_points=talking_points,
        objection_responses=strategy.objection_responses[:3],
        value_proposition=(
            strategy.value_anchors[0] if strategy.value_anchors else ""
        ),
        concession_offered=(
            assessment.concessions_remaining[0]
            if move_type == MoveType.CONCEDE and assessment.concessions_remaining
            else ""
        ),
        confidence=assessment.win_probability,
        approval_required=True,
        execution_allowed=False,
        source_id=source_id,
    )
