"""
Canonical agent cards — the seed list of every agent Hermes recognises.

Each card declares: owner, domain, mission, max sovereignty level,
allowed/forbidden tools, and KPIs. Cards are registered into the
AgentRegistry at boot. Cards alone never execute anything.
"""

from __future__ import annotations

from dealix.hermes.sovereignty.levels import SovereigntyLevel
from dealix.hermes.trust.agent_registry import AgentCard, AgentRegistry


DEFAULT_AGENT_CARDS: list[AgentCard] = [
    # ── Sovereign ────────────────────────────────────────────────
    AgentCard(
        agent_id="chief_of_staff",
        domain="sovereign",
        mission="Brief Sami every morning, flag blockers, queue approvals.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_signals", "read_opportunities", "read_outcomes"],
        forbidden_tools=["send_external", "sign_contract", "transfer_money"],
        kpis=["briefings_delivered", "decisions_recorded"],
    ),
    AgentCard(
        agent_id="money_command",
        domain="sovereign",
        mission="Curate the Money Dashboard and the next-best-action.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_revenue", "read_pipeline", "read_pricing"],
        forbidden_tools=["send_external", "transfer_money"],
        kpis=["money_dashboard_freshness", "best_next_action_accuracy"],
    ),
    AgentCard(
        agent_id="sovereign_decision_journal",
        domain="sovereign",
        mission="Capture every S3+ decision into the journal.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_decisions", "write_journal"],
        kpis=["journal_completeness"],
    ),
    AgentCard(
        agent_id="risk_advisor",
        domain="sovereign",
        mission="Watch the risk register, flag anything escalating.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_risks", "read_incidents"],
        kpis=["risk_escalations_caught"],
    ),
    AgentCard(
        agent_id="capital_allocator",
        domain="sovereign",
        mission="Surface budget vs spend, recommend reallocations.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_capital", "read_revenue"],
        forbidden_tools=["transfer_money"],
        kpis=["bucket_burn_alerts"],
    ),

    # ── Core kernel ──────────────────────────────────────────────
    AgentCard(
        agent_id="signal_classifier",
        domain="core",
        mission="Classify every inbound signal by type and sensitivity.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_signals", "write_signal_classification"],
        kpis=["signals_classified", "classification_accuracy"],
    ),
    AgentCard(
        agent_id="opportunity_mapper",
        domain="core",
        mission="Turn promising signals into scored opportunities.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_signals", "write_opportunity"],
        kpis=["opportunities_created", "score_quality"],
    ),
    AgentCard(
        agent_id="decision_memo",
        domain="core",
        mission="Draft a structured memo for every scored opportunity.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_opportunity", "write_decision"],
        kpis=["memos_drafted"],
    ),
    AgentCard(
        agent_id="execution_planner",
        domain="core",
        mission="Plan executions with the right agent, tools, and approval gate.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_decision", "write_execution"],
        kpis=["executions_planned", "approval_compliance"],
    ),
    AgentCard(
        agent_id="outcome_logger",
        domain="core",
        mission="Log the actual outcome of every execution. No execution skips.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_execution", "write_outcome"],
        kpis=["outcomes_logged", "logging_latency_minutes"],
    ),
    AgentCard(
        agent_id="asset_builder",
        domain="core",
        mission="Harvest reusable assets from successful outcomes.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_outcome", "write_asset"],
        kpis=["assets_created", "reuse_count"],
    ),
    AgentCard(
        agent_id="scale_kill",
        domain="core",
        mission="Apply the scale-or-kill verdict to every asset on schedule.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_asset", "write_asset_state"],
        kpis=["scale_kill_decisions"],
    ),

    # ── Money ────────────────────────────────────────────────────
    AgentCard(
        agent_id="cash_scout",
        domain="money",
        mission="Find the next 5,000 SAR Sami can collect this week.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_pipeline", "read_invoices"],
        kpis=["cash_opportunities_surfaced"],
    ),
    AgentCard(
        agent_id="revenue_hunter",
        domain="money",
        mission="Match warm leads to offers, prep proposals for review.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_pipeline", "read_offers", "draft_proposal"],
        forbidden_tools=["send_external"],
        kpis=["proposals_drafted", "proposal_acceptance_rate"],
    ),
    AgentCard(
        agent_id="offer_matcher",
        domain="money",
        mission="Match each opportunity to the highest-fit offer.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_opportunity", "read_offers"],
        kpis=["match_quality"],
    ),
    AgentCard(
        agent_id="proposal_factory",
        domain="money",
        mission="Generate structured commercial proposals.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_opportunity", "read_offer_library", "draft_proposal"],
        forbidden_tools=["send_external", "sign_contract", "export_data"],
        kpis=["proposals_drafted", "proposal_acceptance_rate", "time_saved_minutes"],
    ),
    AgentCard(
        agent_id="pricing",
        domain="money",
        mission="Recommend pricing within sovereign policy bands.",
        max_sovereignty_level=SovereigntyLevel.S3_SOVEREIGN_MEMO,
        allowed_tools=["read_offers", "read_market_signals"],
        forbidden_tools=["publish_pricing"],
        kpis=["pricing_recommendations"],
    ),
    AgentCard(
        agent_id="followup",
        domain="money",
        mission="Track and remind on every open proposal until decision.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_proposals", "draft_followup"],
        forbidden_tools=["send_external"],
        kpis=["followups_drafted", "stale_proposal_rate"],
    ),
    AgentCard(
        agent_id="deal_room",
        domain="money",
        mission="Curate per-deal context, evidence, and next steps.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_deal", "write_deal_state"],
        kpis=["deal_rooms_maintained"],
    ),
    AgentCard(
        agent_id="invoice",
        domain="money",
        mission="Track invoices, detect overdue, prep reminder drafts.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_invoices", "draft_reminder"],
        forbidden_tools=["send_external"],
        kpis=["overdue_detected", "dso_days"],
    ),
    AgentCard(
        agent_id="upsell",
        domain="money",
        mission="Identify upsell candidates from healthy customers.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_customers", "read_usage"],
        kpis=["upsell_candidates_surfaced"],
    ),

    # ── Growth ───────────────────────────────────────────────────
    AgentCard(
        agent_id="market_radar",
        domain="growth",
        mission="Watch the market for new pain signals.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_open_data", "read_competitor_signals"],
        kpis=["radar_signals_emitted"],
    ),
    AgentCard(
        agent_id="icp_research",
        domain="growth",
        mission="Build and refresh ICP definitions and pain hypotheses.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_signals", "write_icp"],
        kpis=["icp_refreshes"],
    ),
    AgentCard(
        agent_id="campaign_planner",
        domain="growth",
        mission="Plan campaigns tied to a single ICP × offer × channel.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_icp", "read_offers", "write_campaign"],
        forbidden_tools=["send_external"],
        kpis=["campaigns_planned"],
    ),
    AgentCard(
        agent_id="copywriter",
        domain="growth",
        mission="Draft on-brand copy. Never publish.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_offers", "read_icp"],
        forbidden_tools=["send_external", "publish_landing"],
        kpis=["drafts_produced"],
    ),
    AgentCard(
        agent_id="attribution",
        domain="growth",
        mission="Link revenue to campaigns and channels.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_revenue", "read_campaigns", "write_attribution"],
        kpis=["attribution_coverage"],
    ),
    AgentCard(
        agent_id="conversion_optimizer",
        domain="growth",
        mission="Identify drop-offs and propose experiments.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_funnels", "write_experiment"],
        kpis=["experiments_proposed"],
    ),
    AgentCard(
        agent_id="case_study",
        domain="growth",
        mission="Draft case studies from wins. Approval before publish.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_outcomes", "draft_case_study"],
        forbidden_tools=["publish_case_study"],
        kpis=["case_studies_drafted"],
    ),

    # ── Trust ────────────────────────────────────────────────────
    AgentCard(
        agent_id="policy_agent",
        domain="trust",
        mission="Evaluate proposed actions against the policy engine.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_policies", "evaluate_policy"],
        kpis=["policy_evaluations"],
    ),
    AgentCard(
        agent_id="permission_agent",
        domain="trust",
        mission="Check the permission matrix for every tool call.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_permission_matrix"],
        kpis=["permission_checks"],
    ),
    AgentCard(
        agent_id="evidence_agent",
        domain="trust",
        mission="Assemble and persist evidence packs.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_sources", "write_evidence_pack"],
        kpis=["packs_assembled"],
    ),
    AgentCard(
        agent_id="audit_agent",
        domain="trust",
        mission="Verify every action wrote an audit entry.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_audit"],
        kpis=["audit_coverage"],
    ),
    AgentCard(
        agent_id="mcp_risk_agent",
        domain="trust",
        mission="Score MCP servers and tools for risk.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_mcp_registry", "scan_descriptor", "vet_semantics"],
        kpis=["servers_reviewed", "anomalies_caught"],
    ),
    AgentCard(
        agent_id="no_overclaim_agent",
        domain="trust",
        mission="Block overclaim and false-partnership language.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_drafts"],
        kpis=["overclaim_blocks"],
    ),
    AgentCard(
        agent_id="data_scope_agent",
        domain="trust",
        mission="Enforce data classification boundaries on every request.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_boundaries"],
        kpis=["boundary_blocks"],
    ),

    # ── Product ──────────────────────────────────────────────────
    AgentCard(
        agent_id="offer_builder",
        domain="product",
        mission="Compose offers from the offer library.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_offer_library", "write_offer_draft"],
        kpis=["offers_drafted"],
    ),
    AgentCard(
        agent_id="landing_page",
        domain="product",
        mission="Draft landing pages. Never publish without approval.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_offer", "draft_landing"],
        forbidden_tools=["publish_landing"],
        kpis=["landing_drafts"],
    ),
    AgentCard(
        agent_id="experiment",
        domain="product",
        mission="Propose offer experiments with metric + kill rule.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_offers", "read_outcomes"],
        kpis=["experiments_proposed"],
    ),
    AgentCard(
        agent_id="roadmap",
        domain="product",
        mission="Maintain the prioritized product roadmap.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_signals", "read_outcomes", "write_roadmap"],
        kpis=["roadmap_freshness_days"],
    ),

    # ── Partner ──────────────────────────────────────────────────
    AgentCard(
        agent_id="partner_scout",
        domain="partner",
        mission="Find candidate partners by ICP × offer.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_market", "write_partner_candidate"],
        kpis=["candidates_surfaced"],
    ),
    AgentCard(
        agent_id="partner_fit_score",
        domain="partner",
        mission="Score every partner candidate against the fit rubric.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_partner_candidate"],
        kpis=["fit_scores_emitted"],
    ),
    AgentCard(
        agent_id="partner_pitch",
        domain="partner",
        mission="Draft partner pitches. Never send.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_partner", "draft_pitch"],
        forbidden_tools=["send_external"],
        kpis=["pitches_drafted"],
    ),
    AgentCard(
        agent_id="partner_onboarding",
        domain="partner",
        mission="Run signed partners through onboarding checklist.",
        max_sovereignty_level=SovereigntyLevel.S1_INTERNAL,
        allowed_tools=["read_partner", "write_partner_state"],
        kpis=["partners_onboarded"],
    ),
    AgentCard(
        agent_id="partner_performance",
        domain="partner",
        mission="Track partner-attributed revenue and health.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_partner", "read_revenue"],
        kpis=["partner_attributed_revenue"],
    ),

    # ── Customer ─────────────────────────────────────────────────
    AgentCard(
        agent_id="customer_health_score",
        domain="customer",
        mission="Compute a daily health score per customer.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_customer", "read_usage"],
        kpis=["scores_emitted"],
    ),
    AgentCard(
        agent_id="customer_value_report",
        domain="customer",
        mission="Draft value reports for every paid customer.",
        max_sovereignty_level=SovereigntyLevel.S2_SAMI_APPROVAL,
        allowed_tools=["read_customer", "draft_value_report"],
        forbidden_tools=["send_external"],
        kpis=["value_reports_drafted"],
    ),
    AgentCard(
        agent_id="customer_renewal",
        domain="customer",
        mission="Surface upcoming renewals 60 days before.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_customer", "read_contracts"],
        kpis=["renewal_alerts"],
    ),
    AgentCard(
        agent_id="customer_churn_risk",
        domain="customer",
        mission="Flag customers showing churn signals.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_customer", "read_usage", "read_tickets"],
        kpis=["churn_flags"],
    ),

    # ── Venture ──────────────────────────────────────────────────
    AgentCard(
        agent_id="vertical_launcher",
        domain="venture",
        mission="Launch new verticals with first-50 targets and kill rule.",
        max_sovereignty_level=SovereigntyLevel.S3_SOVEREIGN_MEMO,
        allowed_tools=["read_market", "write_vertical_card"],
        kpis=["verticals_launched"],
    ),
    AgentCard(
        agent_id="venture_portfolio",
        domain="venture",
        mission="Track all live verticals and their state.",
        max_sovereignty_level=SovereigntyLevel.S0_AUTO_SAFE,
        allowed_tools=["read_ventures"],
        kpis=["portfolio_health"],
    ),
    AgentCard(
        agent_id="acquisition_scout",
        domain="venture",
        mission="Surface acquisition / acquihire candidates.",
        max_sovereignty_level=SovereigntyLevel.S3_SOVEREIGN_MEMO,
        allowed_tools=["read_market"],
        kpis=["candidates_surfaced"],
    ),
]


def register_default_agents(registry: AgentRegistry) -> list[str]:
    """Register all default cards into a registry. Returns registered ids."""
    return [registry.register(card).agent_id for card in DEFAULT_AGENT_CARDS]
