"""خادم Hermes — Universal Kernel public API.

Top-level surface for Wave 1. Stable imports:

    from dealix.hermes import (
        HermesOrchestrator, EventBus, Event, EventType,
        Signal, Opportunity, Decision, Outcome, Asset,
        Sovereignty, SovereigntyLevel,
    )
"""

from __future__ import annotations

from dealix.hermes.core import (
    Asset,
    AssetBuilder,
    AssetType,
    Decision,
    DecisionMemoBuilder,
    DecisionStatus,
    EntityRef,
    ExecutionPlan,
    ExecutionPlanner,
    ExecutionResult,
    ExecutionStep,
    Money,
    Opportunity,
    OpportunityMapper,
    OpportunityType,
    Outcome,
    OutcomeKind,
    OutcomeLogger,
    RiskLevel,
    ScaleKillKind,
    ScaleKillRecommendation,
    ScaleKillRecommender,
    ScoredOpportunity,
    Signal,
    SignalCategory,
    SignalClassification,
    SignalClassifier,
    SignalSource,
    Tag,
    Timestamps,
    WorkspaceScope,
    opportunity_score,
    partner_fit_score,
    risk_score,
)
from dealix.hermes.events import Event, EventBus, EventType
from dealix.hermes.orchestrator import (
    HermesOrchestrator,
    OrchestratorRun,
    RunStatus,
)
from dealix.hermes.sovereignty import (
    Sovereignty,
    SovereigntyLevel,
    SovereigntyVerdict,
    is_blocking,
    requires_evidence_pack,
)

__all__ = [
    "Asset",
    "AssetBuilder",
    "AssetType",
    "Decision",
    "DecisionMemoBuilder",
    "DecisionStatus",
    "EntityRef",
    "Event",
    "EventBus",
    "EventType",
    "ExecutionPlan",
    "ExecutionPlanner",
    "ExecutionResult",
    "ExecutionStep",
    "HermesOrchestrator",
    "Money",
    "Opportunity",
    "OpportunityMapper",
    "OpportunityType",
    "OrchestratorRun",
    "Outcome",
    "OutcomeKind",
    "OutcomeLogger",
    "RiskLevel",
    "RunStatus",
    "ScaleKillKind",
    "ScaleKillRecommendation",
    "ScaleKillRecommender",
    "ScoredOpportunity",
    "Signal",
    "SignalCategory",
    "SignalClassification",
    "SignalClassifier",
    "SignalSource",
    "Sovereignty",
    "SovereigntyLevel",
    "SovereigntyVerdict",
    "Tag",
    "Timestamps",
    "WorkspaceScope",
    "is_blocking",
    "opportunity_score",
    "partner_fit_score",
    "requires_evidence_pack",
    "risk_score",
]
