"""15-sector Saudi market vertical scoring for the Dealix launch OS.

Each VerticalScore reflects:
  revenue_potential  0-25   SAR market size + deal density
  pain_clarity       0-25   how well-defined the problem is
  regulatory_ease    0-20   low bureaucracy friction
  ai_readiness       0-15   existing digitisation level
  competition_gap    0-15   absence of strong incumbents

Total 0-100.  Scores are pre-researched; they are not generated by an LLM.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class VerticalScore:
    """Scored representation of one Saudi market sector.

    Examples:
        >>> v = VerticalScore(
        ...     sector="automotive",
        ...     revenue_potential=22,
        ...     pain_clarity=22,
        ...     regulatory_ease=16,
        ...     ai_readiness=14,
        ...     competition_gap=12,
        ...     notes_ar="قطاع السيارات يعاني من ضعف متابعة العملاء المحتملين",
        ...     notes_en="High lead volume with poor follow-up discipline",
        ... )
        >>> v.total_score
        86
    """

    sector: str
    revenue_potential: int
    pain_clarity: int
    regulatory_ease: int
    ai_readiness: int
    competition_gap: int
    notes_ar: str = ""
    notes_en: str = ""

    @property
    def total_score(self) -> int:
        return (
            self.revenue_potential
            + self.pain_clarity
            + self.regulatory_ease
            + self.ai_readiness
            + self.competition_gap
        )


# Pre-scored 15 sectors.  Scores are deterministic research judgements.
SAUDI_VERTICALS: list[VerticalScore] = [
    VerticalScore(
        sector="automotive",
        revenue_potential=22,
        pain_clarity=23,
        regulatory_ease=17,
        ai_readiness=14,
        competition_gap=12,
        notes_ar="ضعف متابعة العملاء المحتملين وتتبع المبيعات يدوياً",
        notes_en="Weak lead follow-up; manual sales tracking; high ticket size",
    ),
    VerticalScore(
        sector="real_estate",
        revenue_potential=24,
        pain_clarity=22,
        regulatory_ease=14,
        ai_readiness=13,
        competition_gap=11,
        notes_ar="حجم إعلانات كبير مع ضعف في تأهيل العملاء وإغلاق الصفقات",
        notes_en="Large ad spend with poor lead qualification and deal closing",
    ),
    VerticalScore(
        sector="contracting",
        revenue_potential=21,
        pain_clarity=22,
        regulatory_ease=13,
        ai_readiness=11,
        competition_gap=14,
        notes_ar="إدارة مشاريع يدوية وضعف في تتبع التدفق النقدي",
        notes_en="Manual project management; cash-flow visibility gaps",
    ),
    VerticalScore(
        sector="healthcare_clinics",
        revenue_potential=20,
        pain_clarity=21,
        regulatory_ease=12,
        ai_readiness=13,
        competition_gap=13,
        notes_ar="ضعف في تذكير المواعيد ومتابعة المرضى بعد الزيارة",
        notes_en="Poor appointment reminders; low post-visit follow-up rate",
    ),
    VerticalScore(
        sector="food_and_beverage",
        revenue_potential=20,
        pain_clarity=20,
        regulatory_ease=16,
        ai_readiness=12,
        competition_gap=12,
        notes_ar="ضعف إدارة السمعة الإلكترونية والمبيعات التكرارية",
        notes_en="Online reputation management gaps; weak repeat-purchase systems",
    ),
    VerticalScore(
        sector="education",
        revenue_potential=19,
        pain_clarity=20,
        regulatory_ease=11,
        ai_readiness=14,
        competition_gap=12,
        notes_ar="تحويل العملاء المحتملين للتسجيل يحتاج أتمتة",
        notes_en="Lead-to-enrolment conversion needs automation",
    ),
    VerticalScore(
        sector="retail_chains",
        revenue_potential=21,
        pain_clarity=19,
        regulatory_ease=15,
        ai_readiness=13,
        competition_gap=10,
        notes_ar="ضعف برامج الولاء وتتبع المخزون",
        notes_en="Weak loyalty programs; inventory visibility issues",
    ),
    VerticalScore(
        sector="logistics",
        revenue_potential=19,
        pain_clarity=20,
        regulatory_ease=15,
        ai_readiness=13,
        competition_gap=11,
        notes_ar="ضعف تتبع الشحنات وتواصل العملاء في الوقت الحقيقي",
        notes_en="Real-time shipment visibility and proactive customer comms gaps",
    ),
    VerticalScore(
        sector="professional_services",
        revenue_potential=18,
        pain_clarity=20,
        regulatory_ease=16,
        ai_readiness=12,
        competition_gap=13,
        notes_ar="ضعف في اكتساب العملاء الجدد وتوثيق القيمة",
        notes_en="Client acquisition and value documentation weaknesses",
    ),
    VerticalScore(
        sector="financial_services",
        revenue_potential=20,
        pain_clarity=18,
        regulatory_ease=9,
        ai_readiness=15,
        competition_gap=9,
        notes_ar="رقابة تنظيمية عالية تبطئ الدورة لكن الطلب كبير",
        notes_en="High regulatory scrutiny slows cycle; strong underlying demand",
    ),
    VerticalScore(
        sector="legal",
        revenue_potential=16,
        pain_clarity=19,
        regulatory_ease=10,
        ai_readiness=10,
        competition_gap=14,
        notes_ar="اكتساب العملاء والبرهان على القيمة منخفضان جداً",
        notes_en="Client acquisition and proof-of-value are under-served",
    ),
    VerticalScore(
        sector="hospitality",
        revenue_potential=18,
        pain_clarity=18,
        regulatory_ease=14,
        ai_readiness=12,
        competition_gap=10,
        notes_ar="ضعف إدارة المراجعات وبرامج إعادة الحجز",
        notes_en="Review management and re-booking programs are weak",
    ),
    VerticalScore(
        sector="manufacturing",
        revenue_potential=17,
        pain_clarity=17,
        regulatory_ease=12,
        ai_readiness=10,
        competition_gap=12,
        notes_ar="دورات مبيعات طويلة وضعف في توثيق عروض الأسعار",
        notes_en="Long sales cycles; quotation documentation bottlenecks",
    ),
    VerticalScore(
        sector="government",
        revenue_potential=14,
        pain_clarity=15,
        regulatory_ease=7,
        ai_readiness=11,
        competition_gap=10,
        notes_ar="دورات شراء طويلة ومتطلبات تأهل عالية",
        notes_en="Very long procurement cycles; high qualification requirements",
    ),
    VerticalScore(
        sector="telecom",
        revenue_potential=15,
        pain_clarity=14,
        regulatory_ease=10,
        ai_readiness=15,
        competition_gap=7,
        notes_ar="المنافسة عالية لكن فرص التخصيص للشركات الصغيرة ممكنة",
        notes_en="High competition; niche SMB personalisation opportunity",
    ),
]


def rank_verticals() -> list[VerticalScore]:
    """Return SAUDI_VERTICALS sorted descending by total_score.

    Examples:
        >>> ranked = rank_verticals()
        >>> len(ranked)
        15
        >>> ranked[0].total_score >= ranked[-1].total_score
        True
    """
    return sorted(SAUDI_VERTICALS, key=lambda v: v.total_score, reverse=True)


def top_wedge() -> VerticalScore:
    """Return the highest-scoring sector — the recommended entry wedge.

    Examples:
        >>> w = top_wedge()
        >>> isinstance(w.sector, str)
        True
        >>> w.total_score >= 80
        True
    """
    return rank_verticals()[0]


if __name__ == "__main__":
    import doctest
    results = doctest.testmod(verbose=False)
    print(f"Vertical scorer doctests: {results.attempted} run, {results.failed} failed")

    ranked = rank_verticals()
    print(f"\nTop 5 verticals:")
    for v in ranked[:5]:
        print(f"  {v.sector:<25} score={v.total_score}")
    print(f"\nRecommended entry wedge: {top_wedge().sector}")
