"""Generate a text daily brief from a pipeline snapshot dict."""
from __future__ import annotations

from datetime import date


def generate_brief(snapshot: dict) -> str:
    """Return a markdown-formatted daily brief from *snapshot*.

    Accepted keys (all optional, with sensible defaults):
    - leads (int): number of active leads in pipeline
    - drafts (int): number of email/proposal drafts ready for review
    - calls (int): discovery/follow-up calls scheduled today
    - projects (list[dict]): active projects; each dict may have keys
      ``name`` (str) and ``at_risk`` (bool)
    - cash_sar (int|float): current cash position in SAR
    - pipeline_value_sar (int|float): total open pipeline value in SAR
    - top_leads (list[str]): names of top 3 lead companies

    Returns a non-empty markdown string.
    """
    today = date.today().isoformat()

    leads: int = snapshot.get("leads", 0)
    drafts: int = snapshot.get("drafts", 0)
    calls: int = snapshot.get("calls", 0)
    cash_sar: float = snapshot.get("cash_sar", 0)
    pipeline_value_sar: float = snapshot.get("pipeline_value_sar", 0)
    top_leads: list[str] = snapshot.get("top_leads", [])
    projects: list[dict] = snapshot.get("projects", [])

    # Build top leads section
    if top_leads:
        leads_lines = "\n".join(f"- {lead}" for lead in top_leads[:3])
    else:
        leads_lines = "- No leads specified in snapshot"

    # Build projects at risk section
    at_risk = [p for p in projects if p.get("at_risk", False)]
    if at_risk:
        risk_lines = "\n".join(f"- {p.get('name', 'Unnamed project')}" for p in at_risk)
    elif projects:
        risk_lines = "- No projects currently flagged at risk"
    else:
        risk_lines = "- No active projects in snapshot"

    cash_display = f"{cash_sar:,.0f} SAR" if cash_sar else "Not specified"
    pipeline_display = f"{pipeline_value_sar:,.0f} SAR" if pipeline_value_sar else "Not specified"

    brief = f"""# Dealix Daily Brief — {today}

## Revenue Pipeline Summary

- Active leads in pipeline: {leads}
- Open pipeline value: {pipeline_display}
- Email/proposal drafts ready for review: {drafts}
- Discovery/follow-up calls scheduled today: {calls}

## Top 3 Leads

{leads_lines}

## Drafts Ready for Founder Review

{drafts} draft(s) are ready. Review and approve before sending.

## Calls Scheduled Today

{calls} call(s) on the calendar today.

## Projects at Risk

{risk_lines}

## Cash Forecast

Current cash position: {cash_display}

---
*Generated by Dealix OS Runtime. All outbound actions require founder approval.*
"""
    return brief
