"""approval_center_snapshots — durable approval queue

The approval queue previously lived only in process memory, so every restart
or deploy silently discarded pending approvals. PostgresApprovalStore keeps a
single JSON snapshot row; this creates the table it needs.

Written by hand rather than autogenerated: postgres_store.py declares its own
DeclarativeBase, so it is not part of db.models' metadata and alembic's
autogenerate does not see it.

Revision ID: 20260726_019_approval_center_snapshots
Revises: 20260723_018_communication_hub_storage
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "20260726_019_approval_center_snapshots"
down_revision: str | None = "20260723_018_communication_hub_storage"
branch_labels: str | None = None
depends_on: str | None = None

TABLE_NAME = "approval_center_snapshots"


def upgrade() -> None:
    bind = op.get_bind()
    if sa.inspect(bind).has_table(TABLE_NAME):
        # PostgresApprovalStore calls create_all() on construction, so the
        # table may already exist in environments that ran it before this
        # migration landed. Creating it again would abort the upgrade.
        return

    op.create_table(
        TABLE_NAME,
        sa.Column("id", sa.String(length=64), primary_key=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(sa.dialects.postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )


def downgrade() -> None:
    bind = op.get_bind()
    if sa.inspect(bind).has_table(TABLE_NAME):
        op.drop_table(TABLE_NAME)
