export const serviceCatalogSnapshot = {
  "generated_at": "2026-07-16T09:38:13.210081+00:00",
  "total_offerings": 17,
  "is_estimate": true,
  "funnel_offerings": [
    {
      "id": "free_mini_diagnostic",
      "name_ar": "التشخيص المجاني المختصر",
      "name_en": "Free Mini Diagnostic",
      "price_sar": 0.0,
      "price_unit": "one_time",
      "duration_days": 1,
      "customer_journey_stage": "discovery",
      "deliverables": [
        "1-page sector-fit analysis",
        "3 ranked opportunities",
        "1 Arabic message draft",
        "1 best channel recommendation",
        "1 risk to avoid",
        "1 next-step decision passport"
      ],
      "kpi_commitment_en": "Delivered within 24 hours of form submission.",
      "kpi_commitment_ar": "نسلّم خلال 24 ساعة من تعبئة النموذج.",
      "refund_policy_en": "Free — no payment.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof"
      ],
      "is_estimate": true
    },
    {
      "id": "revenue_proof_sprint_499",
      "name_ar": "سبرنت إثبات الإيرادات (٤٩٩ ر.س)",
      "name_en": "499 SAR Revenue Proof Sprint",
      "price_sar": 499.0,
      "price_unit": "one_time",
      "duration_days": 7,
      "customer_journey_stage": "first_paid",
      "deliverables": [
        "Company Brain v1",
        "Top 10 Opportunities (ranked)",
        "Decision Passports for top 3",
        "Arabic Draft Pack (5 messages)",
        "Follow-up Plan (7-day timeline)",
        "Risk + Objection Map",
        "Executive Pack",
        "Proof Pack",
        "Next Best Offer recommendation"
      ],
      "kpi_commitment_en": "We deliver the approved scope and outputs within the agreed schedule, separating facts, hypotheses, and data gaps.",
      "kpi_commitment_ar": "نلتزم بتسليم النطاق والمخرجات المعتمدة ضمن الجدول المتفق عليه، مع فصل الحقائق والفرضيات وفجوات البيانات.",
      "refund_policy_en": "Refund or service-credit terms are defined in the approved order form; business outcomes are not promised automatically.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_linkedin_auto",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true
    },
    {
      "id": "data_to_revenue_pack_1500",
      "name_ar": "حزمة من البيانات إلى الإيراد (١٥٠٠ ر.س)",
      "name_en": "Data-to-Revenue Pack",
      "price_sar": 1500.0,
      "price_unit": "one_time",
      "duration_days": 14,
      "customer_journey_stage": "expansion",
      "deliverables": [
        "Clean Lead Board (deduplicated)",
        "Duplicate Report",
        "Source Validation Report",
        "Risk Report",
        "Top 20 Opportunities (scored)",
        "10 Arabic Drafts",
        "Follow-up Plan",
        "Decision Passports for top 5"
      ],
      "kpi_commitment_en": "We clean the agreed dataset and document duplicates, provenance, and quality; no opportunity count is promised without customer validation.",
      "kpi_commitment_ar": "نلتزم بتنظيف البيانات المتفق عليها وتوثيق التكرار والمصدر والجودة، ولا نعد بعدد فرص دون اعتماد العميل.",
      "refund_policy_en": "Remedies for undelivered scope are defined in the approved order form and are separate from business outcomes.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true
    },
    {
      "id": "growth_ops_monthly_2999",
      "name_ar": "عمليات النمو الشهرية (٢٩٩٩ ر.س / شهر)",
      "name_en": "Growth Ops Monthly",
      "price_sar": 2999.0,
      "price_unit": "per_month",
      "duration_days": 120,
      "customer_journey_stage": "monthly",
      "deliverables": [
        "4 Weekly Pipeline Audits",
        "Weekly Lead Board",
        "Approval Queue (daily)",
        "Draft Pack (≥20 messages/month)",
        "Support Insights",
        "Proof Events (ongoing)",
        "Monthly Proof Pack",
        "Monthly Executive Summary",
        "Expansion Recommendation"
      ],
      "kpi_commitment_en": "We deliver a weekly operating cadence, approval-gated drafts, and baseline/after measurement; reply-rate lift is a measured hypothesis.",
      "kpi_commitment_ar": "نلتزم بإيقاع تشغيلي أسبوعي، ومسودات خاضعة للموافقة، وقياس خط أساس ونتيجة؛ أي تحسن في الردود فرضية تُقاس ولا تُضمن.",
      "refund_policy_en": "Cancellation, refund, and service-credit terms are defined in the approved contract against delivered scope.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_linkedin_auto",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true
    },
    {
      "id": "support_os_addon_1500",
      "name_ar": "دعم Support OS (١٥٠٠ ر.س / شهر)",
      "name_en": "Support OS Add-on",
      "price_sar": 1500.0,
      "price_unit": "per_month",
      "duration_days": 30,
      "customer_journey_stage": "support_addon",
      "deliverables": [
        "Ticket Classification (12 categories)",
        "Suggested Replies (draft_only)",
        "Escalation List (weekly)",
        "Root Cause Map",
        "Customer Health Score updates",
        "Support Proof Events",
        "SLA breach alerts"
      ],
      "kpi_commitment_en": "We deliver ticket classification, reply drafts, alerts, and response-time measurement; any time target is approved after baseline.",
      "kpi_commitment_ar": "نلتزم بتصنيف التذاكر ومسودات الرد والتنبيهات وقياس زمن الاستجابة؛ أي هدف زمني يعتمد في أمر العمل بعد baseline.",
      "refund_policy_en": "Remedies for delivery failure are defined in the order form; service targets require a baseline and explicit approval.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof"
      ],
      "is_estimate": true
    },
    {
      "id": "executive_command_center_7500",
      "name_ar": "غرفة قيادة الإدارة (٧٥٠٠ ر.س / شهر)",
      "name_en": "Executive Command Center",
      "price_sar": 7500.0,
      "price_unit": "per_month",
      "duration_days": 120,
      "customer_journey_stage": "executive",
      "deliverables": [
        "Daily founder brief (WhatsApp)",
        "Weekly Pipeline Audit",
        "Monthly board pack",
        "Revenue Radar (live)",
        "Sales Pipeline view",
        "Growth Signals dashboard",
        "Support Health overview",
        "Delivery Progress tracker",
        "Payment State view",
        "Proof Ledger access",
        "Approval Queue (daily)",
        "Risk register (weekly)",
        "Next 7 days plan"
      ],
      "kpi_commitment_en": "We deliver an executive readout, decision/risk log, and next-action cadence; time savings are measured from the customer baseline.",
      "kpi_commitment_ar": "نلتزم بقراءة تنفيذية وسجل قرار ومخاطر وإجراء تالٍ؛ وفر الوقت يُقاس من baseline العميل ولا يُضمن.",
      "refund_policy_en": "Cancellation, refund, and service-credit terms follow the approved contract and delivered scope.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_linkedin_auto",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true
    },
    {
      "id": "agency_partner_os",
      "name_ar": "نظام الشريك الوكالة",
      "name_en": "Agency Partner OS",
      "price_sar": 0.0,
      "price_unit": "custom",
      "duration_days": 0,
      "customer_journey_stage": "channel",
      "deliverables": [
        "Partner Intake doc",
        "Co-branded Diagnostic",
        "Client Proof Sprint (per client)",
        "Proof Pack (per client)",
        "Renewal / Upsell Pack",
        "Partner Revenue Tracking",
        "30% commission tracking"
      ],
      "kpi_commitment_en": "30% commission for first paid year per referred customer. Never publish proof without signed consent.",
      "kpi_commitment_ar": "نلتزم بـ٣٠٪ عمولة لأول سنة من كل عميل محوّل. ولا نشر proof بدون موافقة موقّعة.",
      "refund_policy_en": "Formal contract with cancellation terms — lawyer-reviewed.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_linkedin_auto",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true
    }
  ],
  "transformation_offerings": [
    {
      "id": "ai_command_center_os",
      "name_ar": "مركز القيادة الذكي للأعمال",
      "name_en": "AI Business Command Center",
      "price_sar": 35000.0,
      "price_unit": "one_time",
      "duration_days": 60,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Executive command dashboard (Arabic-first)",
        "Daily action board across sales / follow-up / reviews / proposals",
        "Weekly executive report",
        "KPI definitions + semantic metric layer",
        "Team operating cadence",
        "Approval queue wired to governance"
      ],
      "kpi_commitment_en": "We commit to a unified daily executive view live within the setup window. Prices are estimate ranges, finalized after a paid diagnostic.",
      "kpi_commitment_ar": "نلتزم بإطلاق رؤية يومية موحّدة للإدارة خلال مدة الإعداد. الأسعار نطاقات تقديرية تُحدَّد بعد جلسة تشخيص مدفوعة.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 120000.0,
      "price_monthly_sar_min": 8000.0,
      "price_monthly_sar_max": 35000.0
    },
    {
      "id": "whatsapp_revenue_os",
      "name_ar": "نظام إيرادات واتساب",
      "name_en": "WhatsApp Revenue OS",
      "price_sar": 12000.0,
      "price_unit": "one_time",
      "duration_days": 30,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Lead intake model + pipeline stages",
        "Follow-up task system (approval-gated drafts)",
        "Approved message templates (draft_only)",
        "Booking + reporting flow",
        "Lost-reason analysis",
        "Weekly pipeline report"
      ],
      "kpi_commitment_en": "We commit to turning WhatsApp into a measurable pipeline within the setup window. Every external message is an approval-gated draft — no cold send, no automation.",
      "kpi_commitment_ar": "نلتزم بتحويل واتساب إلى pipeline قابل للقياس خلال مدة الإعداد. كل رسالة خارجية مسودة تتطلب موافقة — لا إرسال بارد ولا أتمتة.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_linkedin_auto",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 45000.0,
      "price_monthly_sar_min": 3000.0,
      "price_monthly_sar_max": 15000.0
    },
    {
      "id": "brand_intelligence_os",
      "name_ar": "نظام ذكاء العلامة التجارية",
      "name_en": "Brand Intelligence OS",
      "price_sar": 15000.0,
      "price_unit": "one_time",
      "duration_days": 45,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Brand strategy + positioning map",
        "Visual identity direction",
        "Tone-of-voice system (AR + EN)",
        "Offer messaging bank",
        "Content pillars + social / landing templates",
        "Brand-safe AI prompt library",
        "Content approval workflow"
      ],
      "kpi_commitment_en": "We commit to a reusable, unified brand operating system within the setup window. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بتسليم نظام هوية موحّد قابل لإعادة الاستخدام خلال مدة الإعداد. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true,
      "price_sar_max": 60000.0,
      "price_monthly_sar_min": 4000.0,
      "price_monthly_sar_max": 18000.0
    },
    {
      "id": "ai_agent_workforce_os",
      "name_ar": "نظام قوى العمل من وكلاء الذكاء الاصطناعي",
      "name_en": "AI Agent Workforce OS",
      "price_sar": 40000.0,
      "price_unit": "one_time",
      "duration_days": 90,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Agent role map + task boundaries",
        "Human approval gates for high-risk actions",
        "Agent prompts + allowed tools registry",
        "Audit log structure",
        "Weekly agent performance review",
        "Cost + usage monitoring model"
      ],
      "kpi_commitment_en": "We commit to role-scoped agents with clear boundaries, permissions, and human approval on sensitive actions. No autonomous external execution. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بنشر وكلاء بأدوار وحدود وصلاحيات واضحة ومراجعة بشرية للإجراءات الحساسة. لا تنفيذ خارجي تلقائي. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 180000.0,
      "price_monthly_sar_min": 12000.0,
      "price_monthly_sar_max": 60000.0
    },
    {
      "id": "client_experience_os",
      "name_ar": "نظام تجربة العميل",
      "name_en": "Client Experience OS",
      "price_sar": 20000.0,
      "price_unit": "one_time",
      "duration_days": 60,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Customer journey map (first contact → repeat purchase)",
        "Onboarding workflow",
        "Support workflow",
        "Feedback / review capture loop",
        "Retention dashboard",
        "Escalation system"
      ],
      "kpi_commitment_en": "We commit to a unified customer journey from first contact to repeat purchase within the setup window. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بتوحيد رحلة العميل من أول تواصل إلى إعادة الشراء خلال مدة الإعداد. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true,
      "price_sar_max": 80000.0,
      "price_monthly_sar_min": 6000.0,
      "price_monthly_sar_max": 25000.0
    },
    {
      "id": "operations_automation_os",
      "name_ar": "نظام أتمتة العمليات",
      "name_en": "Operations Automation OS",
      "price_sar": 25000.0,
      "price_unit": "one_time",
      "duration_days": 75,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Workflow map + automation blueprint",
        "Approval matrix",
        "Alerts + reminders",
        "Operations dashboard",
        "SOP library",
        "Handoff + escalation flows"
      ],
      "kpi_commitment_en": "We commit to automating repeatable operations with governance, alerts, and dashboards within the setup window. Map first, then automate — never automate chaos. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بأتمتة العمليات المتكررة بحوكمة وتنبيهات ولوحات خلال مدة الإعداد. نُخرِّط أولاً ثم نؤتمت — لا نؤتمت الفوضى. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true,
      "price_sar_max": 120000.0,
      "price_monthly_sar_min": 7000.0,
      "price_monthly_sar_max": 35000.0
    },
    {
      "id": "executive_reporting_os",
      "name_ar": "نظام التقارير التنفيذية",
      "name_en": "Executive Reporting OS",
      "price_sar": 18000.0,
      "price_unit": "one_time",
      "duration_days": 45,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "KPI model + data source map",
        "Weekly report template",
        "Monthly executive pack",
        "Insights + recommendations layer",
        "Decision tracker"
      ],
      "kpi_commitment_en": "We commit to converting operational data into weekly + monthly executive reports tied to decisions within the setup window. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بتحويل بيانات التشغيل إلى تقارير تنفيذية أسبوعية وشهرية تربط بالقرار خلال مدة الإعداد. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true,
      "price_sar_max": 75000.0,
      "price_monthly_sar_min": 5000.0,
      "price_monthly_sar_max": 20000.0
    },
    {
      "id": "trust_governance_os",
      "name_ar": "نظام الثقة وحوكمة الذكاء الاصطناعي",
      "name_en": "Trust & AI Governance OS",
      "price_sar": 30000.0,
      "price_unit": "one_time",
      "duration_days": 60,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "AI usage policy",
        "Data handling map",
        "Agent risk register",
        "Approval matrix",
        "Monitoring checklist",
        "Incident response runbook",
        "Vendor / tool register"
      ],
      "kpi_commitment_en": "We commit to practical AI + data governance aligned with PDPL and risk management, enforceable operationally. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم ببناء حوكمة عملية للذكاء الاصطناعي والبيانات متوائمة مع PDPL وإدارة المخاطر، قابلة للتطبيق التشغيلي. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 150000.0,
      "price_monthly_sar_min": 10000.0,
      "price_monthly_sar_max": 50000.0
    },
    {
      "id": "growth_engine_os",
      "name_ar": "نظام محرك النمو",
      "name_en": "Growth Engine OS",
      "price_sar": 25000.0,
      "price_unit": "one_time",
      "duration_days": 60,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "ICP map + prospecting workflow",
        "Approved-draft outreach packs (draft_only, approval-gated)",
        "Offer ladder + demo script",
        "Proposal templates",
        "Warm-intro drafts (approval-gated)",
        "Pipeline report"
      ],
      "kpi_commitment_en": "We commit to a repeatable growth machine built on approved drafts only. No cold WhatsApp, no LinkedIn automation, no blast, no scraping. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم ببناء آلة نمو قابلة للتكرار عبر مسودات معتمدة فقط. لا واتساب بارد ولا أتمتة LinkedIn ولا إرسال جماعي ولا scraping. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_linkedin_auto",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 100000.0,
      "price_monthly_sar_min": 8000.0,
      "price_monthly_sar_max": 30000.0
    },
    {
      "id": "custom_enterprise_system",
      "name_ar": "نظام مؤسسي مخصص",
      "name_en": "Custom Enterprise System",
      "price_sar": 0.0,
      "price_unit": "custom",
      "duration_days": 0,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Paid discovery sprint",
        "Solution architecture",
        "UX / workflow prototype",
        "Backend / API blueprint",
        "Dashboards + automations",
        "Integrations",
        "Training + SLA"
      ],
      "kpi_commitment_en": "We commit to a bespoke operating system built around the company's workflows, data, and team — starting with a paid discovery sprint. Scope 100,000–500,000+ SAR is an estimate, set in the contract.",
      "kpi_commitment_ar": "نلتزم ببناء نظام تشغيل مخصص حول عمليات الشركة وبياناتها وفريقها، يبدأ بجلسة تشخيص مدفوعة. النطاق ٠٠٠ر١٠٠–٠٠٠ر٥٠٠+ تقديري يُحدَّد بالعقد.",
      "refund_policy_en": "Formal milestone-based contract, lawyer-reviewed.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true,
      "price_monthly_sar_min": 25000.0
    }
  ],
  "all_offerings": [
    {
      "id": "free_mini_diagnostic",
      "name_ar": "التشخيص المجاني المختصر",
      "name_en": "Free Mini Diagnostic",
      "price_sar": 0.0,
      "price_unit": "one_time",
      "duration_days": 1,
      "customer_journey_stage": "discovery",
      "deliverables": [
        "1-page sector-fit analysis",
        "3 ranked opportunities",
        "1 Arabic message draft",
        "1 best channel recommendation",
        "1 risk to avoid",
        "1 next-step decision passport"
      ],
      "kpi_commitment_en": "Delivered within 24 hours of form submission.",
      "kpi_commitment_ar": "نسلّم خلال 24 ساعة من تعبئة النموذج.",
      "refund_policy_en": "Free — no payment.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof"
      ],
      "is_estimate": true
    },
    {
      "id": "revenue_proof_sprint_499",
      "name_ar": "سبرنت إثبات الإيرادات (٤٩٩ ر.س)",
      "name_en": "499 SAR Revenue Proof Sprint",
      "price_sar": 499.0,
      "price_unit": "one_time",
      "duration_days": 7,
      "customer_journey_stage": "first_paid",
      "deliverables": [
        "Company Brain v1",
        "Top 10 Opportunities (ranked)",
        "Decision Passports for top 3",
        "Arabic Draft Pack (5 messages)",
        "Follow-up Plan (7-day timeline)",
        "Risk + Objection Map",
        "Executive Pack",
        "Proof Pack",
        "Next Best Offer recommendation"
      ],
      "kpi_commitment_en": "We deliver the approved scope and outputs within the agreed schedule, separating facts, hypotheses, and data gaps.",
      "kpi_commitment_ar": "نلتزم بتسليم النطاق والمخرجات المعتمدة ضمن الجدول المتفق عليه، مع فصل الحقائق والفرضيات وفجوات البيانات.",
      "refund_policy_en": "Refund or service-credit terms are defined in the approved order form; business outcomes are not promised automatically.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_linkedin_auto",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true
    },
    {
      "id": "data_to_revenue_pack_1500",
      "name_ar": "حزمة من البيانات إلى الإيراد (١٥٠٠ ر.س)",
      "name_en": "Data-to-Revenue Pack",
      "price_sar": 1500.0,
      "price_unit": "one_time",
      "duration_days": 14,
      "customer_journey_stage": "expansion",
      "deliverables": [
        "Clean Lead Board (deduplicated)",
        "Duplicate Report",
        "Source Validation Report",
        "Risk Report",
        "Top 20 Opportunities (scored)",
        "10 Arabic Drafts",
        "Follow-up Plan",
        "Decision Passports for top 5"
      ],
      "kpi_commitment_en": "We clean the agreed dataset and document duplicates, provenance, and quality; no opportunity count is promised without customer validation.",
      "kpi_commitment_ar": "نلتزم بتنظيف البيانات المتفق عليها وتوثيق التكرار والمصدر والجودة، ولا نعد بعدد فرص دون اعتماد العميل.",
      "refund_policy_en": "Remedies for undelivered scope are defined in the approved order form and are separate from business outcomes.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true
    },
    {
      "id": "growth_ops_monthly_2999",
      "name_ar": "عمليات النمو الشهرية (٢٩٩٩ ر.س / شهر)",
      "name_en": "Growth Ops Monthly",
      "price_sar": 2999.0,
      "price_unit": "per_month",
      "duration_days": 120,
      "customer_journey_stage": "monthly",
      "deliverables": [
        "4 Weekly Pipeline Audits",
        "Weekly Lead Board",
        "Approval Queue (daily)",
        "Draft Pack (≥20 messages/month)",
        "Support Insights",
        "Proof Events (ongoing)",
        "Monthly Proof Pack",
        "Monthly Executive Summary",
        "Expansion Recommendation"
      ],
      "kpi_commitment_en": "We deliver a weekly operating cadence, approval-gated drafts, and baseline/after measurement; reply-rate lift is a measured hypothesis.",
      "kpi_commitment_ar": "نلتزم بإيقاع تشغيلي أسبوعي، ومسودات خاضعة للموافقة، وقياس خط أساس ونتيجة؛ أي تحسن في الردود فرضية تُقاس ولا تُضمن.",
      "refund_policy_en": "Cancellation, refund, and service-credit terms are defined in the approved contract against delivered scope.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_linkedin_auto",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true
    },
    {
      "id": "support_os_addon_1500",
      "name_ar": "دعم Support OS (١٥٠٠ ر.س / شهر)",
      "name_en": "Support OS Add-on",
      "price_sar": 1500.0,
      "price_unit": "per_month",
      "duration_days": 30,
      "customer_journey_stage": "support_addon",
      "deliverables": [
        "Ticket Classification (12 categories)",
        "Suggested Replies (draft_only)",
        "Escalation List (weekly)",
        "Root Cause Map",
        "Customer Health Score updates",
        "Support Proof Events",
        "SLA breach alerts"
      ],
      "kpi_commitment_en": "We deliver ticket classification, reply drafts, alerts, and response-time measurement; any time target is approved after baseline.",
      "kpi_commitment_ar": "نلتزم بتصنيف التذاكر ومسودات الرد والتنبيهات وقياس زمن الاستجابة؛ أي هدف زمني يعتمد في أمر العمل بعد baseline.",
      "refund_policy_en": "Remedies for delivery failure are defined in the order form; service targets require a baseline and explicit approval.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof"
      ],
      "is_estimate": true
    },
    {
      "id": "executive_command_center_7500",
      "name_ar": "غرفة قيادة الإدارة (٧٥٠٠ ر.س / شهر)",
      "name_en": "Executive Command Center",
      "price_sar": 7500.0,
      "price_unit": "per_month",
      "duration_days": 120,
      "customer_journey_stage": "executive",
      "deliverables": [
        "Daily founder brief (WhatsApp)",
        "Weekly Pipeline Audit",
        "Monthly board pack",
        "Revenue Radar (live)",
        "Sales Pipeline view",
        "Growth Signals dashboard",
        "Support Health overview",
        "Delivery Progress tracker",
        "Payment State view",
        "Proof Ledger access",
        "Approval Queue (daily)",
        "Risk register (weekly)",
        "Next 7 days plan"
      ],
      "kpi_commitment_en": "We deliver an executive readout, decision/risk log, and next-action cadence; time savings are measured from the customer baseline.",
      "kpi_commitment_ar": "نلتزم بقراءة تنفيذية وسجل قرار ومخاطر وإجراء تالٍ؛ وفر الوقت يُقاس من baseline العميل ولا يُضمن.",
      "refund_policy_en": "Cancellation, refund, and service-credit terms follow the approved contract and delivered scope.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_linkedin_auto",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true
    },
    {
      "id": "agency_partner_os",
      "name_ar": "نظام الشريك الوكالة",
      "name_en": "Agency Partner OS",
      "price_sar": 0.0,
      "price_unit": "custom",
      "duration_days": 0,
      "customer_journey_stage": "channel",
      "deliverables": [
        "Partner Intake doc",
        "Co-branded Diagnostic",
        "Client Proof Sprint (per client)",
        "Proof Pack (per client)",
        "Renewal / Upsell Pack",
        "Partner Revenue Tracking",
        "30% commission tracking"
      ],
      "kpi_commitment_en": "30% commission for first paid year per referred customer. Never publish proof without signed consent.",
      "kpi_commitment_ar": "نلتزم بـ٣٠٪ عمولة لأول سنة من كل عميل محوّل. ولا نشر proof بدون موافقة موقّعة.",
      "refund_policy_en": "Formal contract with cancellation terms — lawyer-reviewed.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_linkedin_auto",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true
    },
    {
      "id": "ai_command_center_os",
      "name_ar": "مركز القيادة الذكي للأعمال",
      "name_en": "AI Business Command Center",
      "price_sar": 35000.0,
      "price_unit": "one_time",
      "duration_days": 60,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Executive command dashboard (Arabic-first)",
        "Daily action board across sales / follow-up / reviews / proposals",
        "Weekly executive report",
        "KPI definitions + semantic metric layer",
        "Team operating cadence",
        "Approval queue wired to governance"
      ],
      "kpi_commitment_en": "We commit to a unified daily executive view live within the setup window. Prices are estimate ranges, finalized after a paid diagnostic.",
      "kpi_commitment_ar": "نلتزم بإطلاق رؤية يومية موحّدة للإدارة خلال مدة الإعداد. الأسعار نطاقات تقديرية تُحدَّد بعد جلسة تشخيص مدفوعة.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 120000.0,
      "price_monthly_sar_min": 8000.0,
      "price_monthly_sar_max": 35000.0
    },
    {
      "id": "whatsapp_revenue_os",
      "name_ar": "نظام إيرادات واتساب",
      "name_en": "WhatsApp Revenue OS",
      "price_sar": 12000.0,
      "price_unit": "one_time",
      "duration_days": 30,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Lead intake model + pipeline stages",
        "Follow-up task system (approval-gated drafts)",
        "Approved message templates (draft_only)",
        "Booking + reporting flow",
        "Lost-reason analysis",
        "Weekly pipeline report"
      ],
      "kpi_commitment_en": "We commit to turning WhatsApp into a measurable pipeline within the setup window. Every external message is an approval-gated draft — no cold send, no automation.",
      "kpi_commitment_ar": "نلتزم بتحويل واتساب إلى pipeline قابل للقياس خلال مدة الإعداد. كل رسالة خارجية مسودة تتطلب موافقة — لا إرسال بارد ولا أتمتة.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_linkedin_auto",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 45000.0,
      "price_monthly_sar_min": 3000.0,
      "price_monthly_sar_max": 15000.0
    },
    {
      "id": "brand_intelligence_os",
      "name_ar": "نظام ذكاء العلامة التجارية",
      "name_en": "Brand Intelligence OS",
      "price_sar": 15000.0,
      "price_unit": "one_time",
      "duration_days": 45,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Brand strategy + positioning map",
        "Visual identity direction",
        "Tone-of-voice system (AR + EN)",
        "Offer messaging bank",
        "Content pillars + social / landing templates",
        "Brand-safe AI prompt library",
        "Content approval workflow"
      ],
      "kpi_commitment_en": "We commit to a reusable, unified brand operating system within the setup window. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بتسليم نظام هوية موحّد قابل لإعادة الاستخدام خلال مدة الإعداد. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true,
      "price_sar_max": 60000.0,
      "price_monthly_sar_min": 4000.0,
      "price_monthly_sar_max": 18000.0
    },
    {
      "id": "ai_agent_workforce_os",
      "name_ar": "نظام قوى العمل من وكلاء الذكاء الاصطناعي",
      "name_en": "AI Agent Workforce OS",
      "price_sar": 40000.0,
      "price_unit": "one_time",
      "duration_days": 90,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Agent role map + task boundaries",
        "Human approval gates for high-risk actions",
        "Agent prompts + allowed tools registry",
        "Audit log structure",
        "Weekly agent performance review",
        "Cost + usage monitoring model"
      ],
      "kpi_commitment_en": "We commit to role-scoped agents with clear boundaries, permissions, and human approval on sensitive actions. No autonomous external execution. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بنشر وكلاء بأدوار وحدود وصلاحيات واضحة ومراجعة بشرية للإجراءات الحساسة. لا تنفيذ خارجي تلقائي. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 180000.0,
      "price_monthly_sar_min": 12000.0,
      "price_monthly_sar_max": 60000.0
    },
    {
      "id": "client_experience_os",
      "name_ar": "نظام تجربة العميل",
      "name_en": "Client Experience OS",
      "price_sar": 20000.0,
      "price_unit": "one_time",
      "duration_days": 60,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Customer journey map (first contact → repeat purchase)",
        "Onboarding workflow",
        "Support workflow",
        "Feedback / review capture loop",
        "Retention dashboard",
        "Escalation system"
      ],
      "kpi_commitment_en": "We commit to a unified customer journey from first contact to repeat purchase within the setup window. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بتوحيد رحلة العميل من أول تواصل إلى إعادة الشراء خلال مدة الإعداد. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true,
      "price_sar_max": 80000.0,
      "price_monthly_sar_min": 6000.0,
      "price_monthly_sar_max": 25000.0
    },
    {
      "id": "operations_automation_os",
      "name_ar": "نظام أتمتة العمليات",
      "name_en": "Operations Automation OS",
      "price_sar": 25000.0,
      "price_unit": "one_time",
      "duration_days": 75,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Workflow map + automation blueprint",
        "Approval matrix",
        "Alerts + reminders",
        "Operations dashboard",
        "SOP library",
        "Handoff + escalation flows"
      ],
      "kpi_commitment_en": "We commit to automating repeatable operations with governance, alerts, and dashboards within the setup window. Map first, then automate — never automate chaos. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بأتمتة العمليات المتكررة بحوكمة وتنبيهات ولوحات خلال مدة الإعداد. نُخرِّط أولاً ثم نؤتمت — لا نؤتمت الفوضى. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true,
      "price_sar_max": 120000.0,
      "price_monthly_sar_min": 7000.0,
      "price_monthly_sar_max": 35000.0
    },
    {
      "id": "executive_reporting_os",
      "name_ar": "نظام التقارير التنفيذية",
      "name_en": "Executive Reporting OS",
      "price_sar": 18000.0,
      "price_unit": "one_time",
      "duration_days": 45,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "KPI model + data source map",
        "Weekly report template",
        "Monthly executive pack",
        "Insights + recommendations layer",
        "Decision tracker"
      ],
      "kpi_commitment_en": "We commit to converting operational data into weekly + monthly executive reports tied to decisions within the setup window. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم بتحويل بيانات التشغيل إلى تقارير تنفيذية أسبوعية وشهرية تربط بالقرار خلال مدة الإعداد. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue"
      ],
      "is_estimate": true,
      "price_sar_max": 75000.0,
      "price_monthly_sar_min": 5000.0,
      "price_monthly_sar_max": 20000.0
    },
    {
      "id": "trust_governance_os",
      "name_ar": "نظام الثقة وحوكمة الذكاء الاصطناعي",
      "name_en": "Trust & AI Governance OS",
      "price_sar": 30000.0,
      "price_unit": "one_time",
      "duration_days": 60,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "AI usage policy",
        "Data handling map",
        "Agent risk register",
        "Approval matrix",
        "Monitoring checklist",
        "Incident response runbook",
        "Vendor / tool register"
      ],
      "kpi_commitment_en": "We commit to practical AI + data governance aligned with PDPL and risk management, enforceable operationally. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم ببناء حوكمة عملية للذكاء الاصطناعي والبيانات متوائمة مع PDPL وإدارة المخاطر، قابلة للتطبيق التشغيلي. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 150000.0,
      "price_monthly_sar_min": 10000.0,
      "price_monthly_sar_max": 50000.0
    },
    {
      "id": "growth_engine_os",
      "name_ar": "نظام محرك النمو",
      "name_en": "Growth Engine OS",
      "price_sar": 25000.0,
      "price_unit": "one_time",
      "duration_days": 60,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "ICP map + prospecting workflow",
        "Approved-draft outreach packs (draft_only, approval-gated)",
        "Offer ladder + demo script",
        "Proposal templates",
        "Warm-intro drafts (approval-gated)",
        "Pipeline report"
      ],
      "kpi_commitment_en": "We commit to a repeatable growth machine built on approved drafts only. No cold WhatsApp, no LinkedIn automation, no blast, no scraping. Prices are estimate ranges.",
      "kpi_commitment_ar": "نلتزم ببناء آلة نمو قابلة للتكرار عبر مسودات معتمدة فقط. لا واتساب بارد ولا أتمتة LinkedIn ولا إرسال جماعي ولا scraping. الأسعار نطاقات تقديرية.",
      "refund_policy_en": "Pro-rata refund for undelivered milestones per the contract.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_linkedin_auto",
        "no_blast"
      ],
      "is_estimate": true,
      "price_sar_max": 100000.0,
      "price_monthly_sar_min": 8000.0,
      "price_monthly_sar_max": 30000.0
    },
    {
      "id": "custom_enterprise_system",
      "name_ar": "نظام مؤسسي مخصص",
      "name_en": "Custom Enterprise System",
      "price_sar": 0.0,
      "price_unit": "custom",
      "duration_days": 0,
      "customer_journey_stage": "transformation",
      "deliverables": [
        "Paid discovery sprint",
        "Solution architecture",
        "UX / workflow prototype",
        "Backend / API blueprint",
        "Dashboards + automations",
        "Integrations",
        "Training + SLA"
      ],
      "kpi_commitment_en": "We commit to a bespoke operating system built around the company's workflows, data, and team — starting with a paid discovery sprint. Scope 100,000–500,000+ SAR is an estimate, set in the contract.",
      "kpi_commitment_ar": "نلتزم ببناء نظام تشغيل مخصص حول عمليات الشركة وبياناتها وفريقها، يبدأ بجلسة تشخيص مدفوعة. النطاق ٠٠٠ر١٠٠–٠٠٠ر٥٠٠+ تقديري يُحدَّد بالعقد.",
      "refund_policy_en": "Formal milestone-based contract, lawyer-reviewed.",
      "hard_gates": [
        "no_live_send",
        "no_live_charge",
        "no_cold_whatsapp",
        "no_scraping",
        "no_fake_proof",
        "no_fake_revenue",
        "no_blast"
      ],
      "is_estimate": true,
      "price_monthly_sar_min": 25000.0
    }
  ]
} as const;
