import { useState } from 'react';
import {
  FileSpreadsheet, Download, Target, BarChart3,
  AlertTriangle, Star, Clock, DollarSign, CheckCircle2
} from 'lucide-react';
import {
  AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, PieChart, Pie, Cell
} from 'recharts';

const weeklyPerformance = [
  { day: 'السبت', revenue: 12000, calls: 5, leads: 3 },
  { day: 'الأحد', revenue: 18000, calls: 8, leads: 5 },
  { day: 'الإثنين', revenue: 22000, calls: 6, leads: 4 },
  { day: 'الثلاثاء', revenue: 25000, calls: 10, leads: 7 },
  { day: 'الأربعاء', revenue: 32000, calls: 7, leads: 6 },
  { day: 'الخميس', revenue: 38000, calls: 9, leads: 8 },
  { day: 'الجمعة', revenue: 8000, calls: 3, leads: 2 },
];

const sectorBreakdown = [
  { name: 'عقارات', value: 35, color: '#1B5E3B' },
  { name: 'صحة', value: 25, color: '#C9A94C' },
  { name: 'تجارة', value: 20, color: '#0D2818' },
  { name: 'تقنية', value: 15, color: '#6B7280' },
  { name: 'صناعة', value: 5, color: '#E5E5E5' },
];

const reportTemplates = [
  { id: 1, name: 'التقرير اليومي', frequency: 'يومي', lastRun: 'اليوم 08:00', status: 'active', description: 'ملخص يومي للمبيعات، المكالمات، والأهداف' },
  { id: 2, name: 'التقرير الأسبوعي', frequency: 'أسبوعي', lastRun: 'الأحد الماضي', status: 'active', description: 'تحليل أداء الأسبوع والمقارنة بالأسبوع السابق' },
  { id: 3, name: 'التقرير الشهري', frequency: 'شهري', lastRun: '1 يونيو', status: 'active', description: 'تقرير شامل للمؤسس شامل جميع الأقسام' },
  { id: 4, name: 'تقرير المبيعات', frequency: 'أسبوعي', lastRun: 'أمس', status: 'paused', description: 'تفاصيل خط الأنابيب والصفقات' },
  { id: 5, name: 'تقرير الاستهداف', frequency: 'يومي', lastRun: 'اليوم 09:00', status: 'active', description: 'نتائج المكالمات والاستهداف اليومي' },
];

const dailyBrief = {
  date: new Date().toLocaleDateString('ar-SA'),
  revenue: 45_000,
  revenueChange: '+18%',
  calls: 48,
  callsChange: '+5',
  meetings: 3,
  newDeals: 2,
  pipeline: 320_000,
  alerts: [
    { type: 'success', message: 'صفقة شركة العقارات الكبرى - 45,000 ريال' },
    { type: 'warning', message: '3 طلبات موافقة معلقة' },
    { type: 'info', message: 'عميل جديد: مستشفى الرياض الوطني' },
  ],
  todayTargets: [
    { task: 'مكالمة - شركة العقارات الكبرى', status: 'done', time: '09:00' },
    { task: 'إرسال عرض - STC Solutions', status: 'in_progress', time: '11:00' },
    { task: 'اجتماع - المستشفى الوطني', status: 'pending', time: '14:00' },
    { task: 'متابعة - شركة التقنية', status: 'pending', time: '16:00' },
  ],
};

export default function ReportsPage() {
  const [activeView, setActiveView] = useState<'brief' | 'reports' | 'analytics'>('brief');
  const [reportType, setReportType] = useState('daily');

  const exportReport = (format: 'txt' | 'json') => {
    const data = {
      type: reportType,
      date: new Date().toISOString(),
      summary: dailyBrief,
      weeklyData: weeklyPerformance,
      sectorBreakdown,
    };
    const blob = new Blob(
      [format === 'json' ? JSON.stringify(data, null, 2) : generateTextReport()],
      { type: format === 'json' ? 'application/json' : 'text/plain' }
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `dealix-report-${reportType}-${new Date().toISOString().split('T')[0]}.${format}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateTextReport = () => {
    return `Dealix Report - ${dailyBrief.date}
============================================

FINANCIAL
---------
Revenue: ${dailyBrief.revenue.toLocaleString()} SAR (${dailyBrief.revenueChange})
Pipeline: ${dailyBrief.pipeline.toLocaleString()} SAR

ACTIVITY
--------
Calls: ${dailyBrief.calls} (${dailyBrief.callsChange})
Meetings: ${dailyBrief.meetings}
New Deals: ${dailyBrief.newDeals}

TODAY'S TARGETS
---------------
${dailyBrief.todayTargets.map(t => `[${t.status === 'done' ? 'x' : ' '}] ${t.task} (${t.time})`).join('\n')}

ALERTS
------
${dailyBrief.alerts.map(a => `[${a.type.toUpperCase()}] ${a.message}`).join('\n')}

Generated by Dealix Founder OS`;
  };

  return (
    <div className="space-y-6" style={{ direction: 'rtl' }}>
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">التقارير المؤتمتة</h1>
          <p className="text-sm text-gray-500 mt-1">تقارير يومية وأسبوعية وشهرية تلقائية</p>
        </div>
        <div className="flex items-center gap-2">
          <select
            value={reportType}
            onChange={(e) => setReportType(e.target.value)}
            className="text-sm border border-gray-200 rounded-lg px-3 py-2"
          >
            <option value="daily">تقرير يومي</option>
            <option value="weekly">تقرير أسبوعي</option>
            <option value="monthly">تقرير شهري</option>
          </select>
          <button onClick={() => exportReport('txt')} className="flex items-center gap-2 px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 text-sm font-bold">
            <Download className="w-4 h-4" /> TXT
          </button>
          <button onClick={() => exportReport('json')} className="flex items-center gap-2 px-4 py-2 bg-dealix-emerald text-white rounded-lg hover:bg-dealix-forest text-sm font-bold">
            <Download className="w-4 h-4" /> JSON
          </button>
        </div>
      </div>

      {/* View Tabs */}
      <div className="flex gap-2">
        {[
          { key: 'brief', label: 'الإيجاز الصباحي', icon: Clock },
          { key: 'analytics', label: 'التحليلات', icon: BarChart3 },
          { key: 'reports', label: 'التقارير المجدولة', icon: FileSpreadsheet },
        ].map((tab) => {
          const Icon = tab.icon;
          return (
            <button
              key={tab.key}
              onClick={() => setActiveView(tab.key as any)}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-bold transition-all ${
                activeView === tab.key ? 'bg-dealix-charcoal text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
              }`}
            >
              <Icon className="w-4 h-4" /> {tab.label}
            </button>
          );
        })}
      </div>

      {/* ===== Morning Brief ===== */}
      {activeView === 'brief' && (
        <div className="space-y-6">
          {/* Hero Stats */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="bg-gradient-to-br from-dealix-emerald to-dealix-forest rounded-xl p-5 text-white">
              <DollarSign className="w-6 h-6 text-dealix-gold mb-2" />
              <p className="text-3xl font-bold">{dailyBrief.revenue.toLocaleString()}</p>
              <p className="text-sm text-white/70">إيرادات اليوم <span className="text-dealix-gold">{dailyBrief.revenueChange}</span></p>
            </div>
            <div className="bg-white rounded-xl p-5 shadow-card border border-gray-100">
              <svg className="w-6 h-6 text-blue-500 mb-2" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>
              <p className="text-3xl font-bold text-gray-900">{dailyBrief.calls}</p>
              <p className="text-sm text-gray-500">مكالمات <span className="text-green-600">+{dailyBrief.callsChange}</span></p>
            </div>
            <div className="bg-white rounded-xl p-5 shadow-card border border-gray-100">
              <Target className="w-6 h-6 text-dealix-gold mb-2" />
              <p className="text-3xl font-bold text-gray-900">{dailyBrief.meetings}</p>
              <p className="text-sm text-gray-500">اجتماعات</p>
            </div>
            <div className="bg-white rounded-xl p-5 shadow-card border border-gray-100">
              <Star className="w-6 h-6 text-purple-500 mb-2" />
              <p className="text-3xl font-bold text-gray-900">{dailyBrief.newDeals}</p>
              <p className="text-sm text-gray-500">صفقات جديدة</p>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Alerts */}
            <div className="bg-white rounded-xl p-6 shadow-card border border-gray-100">
              <h3 className="font-bold text-gray-900 mb-4">تنبيهات اليوم</h3>
              <div className="space-y-3">
                {dailyBrief.alerts.map((alert, i) => (
                  <div key={i} className={`flex items-start gap-3 p-3 rounded-lg ${
                    alert.type === 'success' ? 'bg-green-50 border border-green-100' :
                    alert.type === 'warning' ? 'bg-amber-50 border border-amber-100' :
                    'bg-blue-50 border border-blue-100'
                  }`}>
                    {alert.type === 'success' ? <CheckCircle2 className="w-5 h-5 text-green-600 shrink-0" /> :
                     alert.type === 'warning' ? <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" /> :
                     <Star className="w-5 h-5 text-blue-600 shrink-0" />}
                    <p className="text-sm text-gray-800">{alert.message}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Today's Targets */}
            <div className="bg-white rounded-xl p-6 shadow-card border border-gray-100">
              <h3 className="font-bold text-gray-900 mb-4">أهداف اليوم</h3>
              <div className="space-y-3">
                {dailyBrief.todayTargets.map((target, i) => (
                  <div key={i} className="flex items-center gap-3 p-3 rounded-lg bg-gray-50">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center ${
                      target.status === 'done' ? 'bg-green-500' :
                      target.status === 'in_progress' ? 'bg-dealix-gold' :
                      'bg-gray-300'
                    }`}>
                      {target.status === 'done' ? <CheckCircle2 className="w-4 h-4 text-white" /> :
                       <Clock className="w-4 h-4 text-white" />}
                    </div>
                    <div className="flex-1">
                      <p className={`text-sm font-medium ${target.status === 'done' ? 'line-through text-gray-400' : 'text-gray-800'}`}>
                        {target.task}
                      </p>
                    </div>
                    <span className="text-xs text-gray-400">{target.time}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ===== Analytics ===== */}
      {activeView === 'analytics' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="bg-white rounded-xl p-6 shadow-card border border-gray-100">
              <h3 className="font-bold text-gray-900 mb-4">أداء الأسبوع</h3>
              <ResponsiveContainer width="100%" height={250}>
                <AreaChart data={weeklyPerformance}>
                  <defs><linearGradient id="repGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#1B5E3B" stopOpacity={0.3}/><stop offset="95%" stopColor="#1B5E3B" stopOpacity={0}/></linearGradient></defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                  <XAxis dataKey="day" tick={{fontSize: 12}} />
                  <YAxis tick={{fontSize: 12}} />
                  <Tooltip />
                  <Area type="monotone" dataKey="revenue" stroke="#1B5E3B" fill="url(#repGrad)" name="الإيرادات" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
            <div className="bg-white rounded-xl p-6 shadow-card border border-gray-100">
              <h3 className="font-bold text-gray-900 mb-4">توزيع القطاعات</h3>
              <ResponsiveContainer width="100%" height={200}>
                <PieChart><Pie data={sectorBreakdown} cx="50%" cy="50%" innerRadius={50} outerRadius={80} dataKey="value">
                  {sectorBreakdown.map((e, i) => <Cell key={i} fill={e.color} />)}
                </Pie></PieChart>
              </ResponsiveContainer>
              <div className="grid grid-cols-2 gap-2 mt-4">
                {sectorBreakdown.map((s, i) => (
                  <div key={i} className="flex items-center gap-2 text-sm"><span className="w-2.5 h-2.5 rounded-full" style={{backgroundColor: s.color}} />{s.name} {s.value}%</div>
                ))}
              </div>
            </div>
          </div>

          <div className="bg-white rounded-xl p-6 shadow-card border border-gray-100">
            <h3 className="font-bold text-gray-900 mb-4">المكالمات والعملاء المحتملين</h3>
            <ResponsiveContainer width="100%" height={250}>
              <BarChart data={weeklyPerformance}>
                <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                <XAxis dataKey="day" tick={{fontSize: 12}} />
                <YAxis tick={{fontSize: 12}} />
                <Tooltip />
                <Bar dataKey="calls" fill="#1B5E3B" name="مكالمات" radius={[4, 4, 0, 0]} />
                <Bar dataKey="leads" fill="#C9A94C" name="عملاء" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      )}

      {/* ===== Scheduled Reports ===== */}
      {activeView === 'reports' && (
        <div className="bg-white rounded-xl shadow-card border border-gray-100">
          {reportTemplates.map((report) => (
            <div key={report.id} className="p-6 flex items-center justify-between hover:bg-gray-50 transition-colors border-b border-gray-100 last:border-b-0">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-lg bg-dealix-emerald/10 flex items-center justify-center">
                  <FileSpreadsheet className="w-5 h-5 text-dealix-emerald" />
                </div>
                <div>
                  <h4 className="font-bold text-gray-900">{report.name}</h4>
                  <p className="text-sm text-gray-500 mt-1">{report.description}</p>
                  <div className="flex items-center gap-3 mt-2">
                    <span className="text-xs text-gray-400 flex items-center gap-1"><Clock className="w-3 h-3" /> {report.frequency}</span>
                    <span className="text-xs text-gray-400">آخر تشغيل: {report.lastRun}</span>
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <span className={`text-xs px-2 py-0.5 rounded-full ${
                  report.status === 'active' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'
                }`}>
                  {report.status === 'active' ? 'نشط' : 'متوقف'}
                </span>
                <button className="p-2 bg-gray-50 rounded-lg hover:bg-gray-100">
                  <Download className="w-4 h-4 text-gray-600" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
