"""Weekly GTM review dry-run — renders a weekly board review from sample pipeline.

Run: python scripts/launch/weekly_gtm_review_dry_run.py

No external calls. No mutations. Safe any time.
"""
from __future__ import annotations

import os
import sys
import tempfile
from datetime import date, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))

from dealix.launch_os.pipeline_tracker import PipelineStage, PipelineTracker
from dealix.launch_os.vertical_scorer import rank_verticals, top_wedge


def week_range() -> tuple[date, date]:
    today = date.today()
    start = today - timedelta(days=today.weekday())
    end = start + timedelta(days=6)
    return start, end


def render_weekly_review(tracker: PipelineTracker) -> str:
    week_start, week_end = week_range()
    # pipeline_summary() returns {stage: count}
    by_stage = tracker.pipeline_summary()
    all_items = tracker.list_all()
    total_deals = len(all_items)
    total_arr = sum(i.value_sar for i in all_items)
    wedge = top_wedge()
    top_verticals = rank_verticals()[:3]

    lines = [
        "=" * 70,
        "DEALIX WEEKLY GTM BOARD REVIEW",
        "مراجعة مجلس الإدارة الأسبوعية للنمو",
        f"الأسبوع: {week_start.strftime('%Y-%m-%d')} -> {week_end.strftime('%Y-%m-%d')}",
        "=" * 70,
        "",
        "── أداء خط الأنابيب / Pipeline Performance ──",
        f"  إجمالي الصفقات النشطة / Active Deals:  {total_deals}",
        f"  إجمالي قيمة خط الأنابيب / Total ARR:    {total_arr:,} SAR",
        "",
        "  توزيع المراحل / Stage Distribution:",
    ]

    for stage, count in by_stage.items():
        if count > 0:
            stage_arr = sum(i.value_sar for i in all_items if i.stage == stage)
            lines.append(f"    {stage:<15} {count} deals   {stage_arr:>10,} SAR")

    lines += [
        "",
        "── أولوية القطاع / Vertical Focus ──",
        f"  القطاع الأول / Top Wedge: {wedge.sector} (score: {wedge.total_score}/100)",
        "",
        "  أفضل 3 قطاعات / Top 3 Sectors:",
    ]

    for i, v in enumerate(top_verticals, 1):
        lines.append(f"    {i}. {v.sector:<20} {v.total_score}/100")

    lines += [
        "",
        "── مراجعة الصفقات / Deal Review ──",
    ]

    for stage in [PipelineStage.PROPOSAL, PipelineStage.NEGOTIATION, PipelineStage.DISCOVERY]:
        stage_items = tracker.list_by_stage(stage)
        if stage_items:
            lines.append(f"\n  [{stage}]")
            for item in stage_items:
                lines.append(
                    f"    - {item.company_name:<30} {item.value_sar:>8,} SAR"
                    f"  ICP:{item.icp_score}  -> {item.next_action}"
                )

    lines += [
        "",
        "── الأهداف للأسبوع القادم / Next Week Targets ──",
        "  1. إرسال 5 رسائل تواصل (LinkedIn أو Email)",
        "  2. إجراء 2 مكالمة اكتشاف",
        "  3. نشر 5 منشورات LinkedIn",
        "  4. متابعة كل الصفقات في مرحلة العرض",
        "",
        "── السؤال الإستراتيجي / Strategic Question ──",
        "  هل القطاع الذي نستهدفه يُعطي أفضل النتائج؟",
        "  إذا لا، هل نغير الاستهداف أو نعمق التخصص؟",
        "",
        "=" * 70,
        "Weekly GTM Review — generated by weekly_gtm_review_dry_run.py",
    ]

    return "\n".join(lines)


def main() -> None:
    with tempfile.NamedTemporaryFile(suffix=".jsonl", delete=False) as f:
        tmp_path = f.name

    try:
        tracker = PipelineTracker(path=tmp_path)

        # Seed sample data using current API (account_id, company_name, ...)
        tracker.add("riyadh_realty_01", "شركة الرياض للعقارات",
                    offer_id="WHATSAPP_FOLLOWUP_OS", value_sar=2999, icp_score=84)
        tracker.advance("riyadh_realty_01", to_stage=PipelineStage.PROPOSAL)

        tracker.add("faris_auto_01", "مجموعة الفارس للسيارات",
                    offer_id="REVENUE_LEAK_AUDIT", value_sar=499, icp_score=72)
        tracker.advance("faris_auto_01", to_stage=PipelineStage.OUTREACH)

        tracker.add("modern_build_01", "مقاولات الإنشاء الحديث",
                    offer_id="PROPOSAL_PROOF_PACK_OS", value_sar=1500, icp_score=78)
        tracker.advance("modern_build_01", to_stage=PipelineStage.DISCOVERY)

        tracker.add("dining_chain_01", "سلسلة مطاعم الذوق",
                    offer_id="AI_OPERATING_SYSTEM_FOR_SMB", value_sar=3999, icp_score=75)
        tracker.advance("dining_chain_01", to_stage=PipelineStage.NEGOTIATION)

        print(render_weekly_review(tracker))

    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


if __name__ == "__main__":
    main()
