/**
 * AI wrapper with provider fallback (OpenAI -> Anthropic -> static fallback).
 *
 * NEVER blocks an endpoint if no key is set — always returns an intelligent
 * static response so the entire backend remains usable in dev/seed-only modes.
 */
import { env } from "../env.js";

export interface AIChatOptions {
  systemPrompt?: string;
  userPrompt: string;
  maxTokens?: number;
  temperature?: number;
  language?: "ar" | "en";
}

export interface AIChatResult {
  text: string;
  provider: "openai" | "anthropic" | "fallback";
  model: string;
  cached: boolean;
}

const MAX_RETRIES = 2;

async function callOpenAI(opts: AIChatOptions): Promise<string> {
  const body = {
    model: env.OPENAI_MODEL,
    messages: [
      ...(opts.systemPrompt
        ? [{ role: "system", content: opts.systemPrompt }]
        : []),
      { role: "user", content: opts.userPrompt },
    ],
    temperature: opts.temperature ?? 0.5,
    max_tokens: opts.maxTokens ?? 700,
  };
  const res = await fetch(`${env.OPENAI_BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${env.OPENAI_API_KEY}`,
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    throw new Error(`openai ${res.status}: ${await res.text()}`);
  }
  const json = (await res.json()) as {
    choices: Array<{ message: { content: string } }>;
  };
  return json.choices?.[0]?.message?.content?.trim() || "";
}

async function callAnthropic(opts: AIChatOptions): Promise<string> {
  const body = {
    model: env.ANTHROPIC_MODEL,
    max_tokens: opts.maxTokens ?? 700,
    temperature: opts.temperature ?? 0.5,
    system: opts.systemPrompt,
    messages: [{ role: "user", content: opts.userPrompt }],
  };
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    throw new Error(`anthropic ${res.status}: ${await res.text()}`);
  }
  const json = (await res.json()) as {
    content: Array<{ type: string; text?: string }>;
  };
  return (
    json.content
      ?.filter((c) => c.type === "text")
      .map((c) => c.text || "")
      .join("\n")
      .trim() || ""
  );
}

function staticFallback(opts: AIChatOptions): string {
  const ar = opts.language !== "en";
  if (ar) {
    return [
      "ملاحظة: تم توليد هذا الرد من نموذج محلي احتياطي (لم يُكتشف مزود AI).",
      "",
      "نقاط رئيسية مقترحة بناءً على السياق:",
      "1) ابدأ بفائدة واضحة ومحددة للعميل مرتبطة بأهدافه التجارية.",
      "2) قدّم دليلاً ملموساً (case study أو رقم) من نفس القطاع.",
      "3) اقترح خطوة تالية صغيرة وآمنة (مكالمة 20 دقيقة أو demo قصير).",
      "4) أنهِ برسالة مهذبة، احترام للوقت، واختر CTA واحد فقط.",
    ].join("\n");
  }
  return [
    "Note: Generated by local fallback model (no AI provider detected).",
    "",
    "Suggested talking points based on context:",
    "1) Lead with a concrete benefit tied to the customer's stated goal.",
    "2) Reference one comparable case study or metric from their industry.",
    "3) Propose a small, low-risk next step (20-minute call or focused demo).",
    "4) Close politely with a single, time-respectful CTA.",
  ].join("\n");
}

export async function aiChat(opts: AIChatOptions): Promise<AIChatResult> {
  let lastErr: unknown;

  if (env.OPENAI_API_KEY) {
    for (let i = 0; i < MAX_RETRIES; i++) {
      try {
        const text = await callOpenAI(opts);
        if (text) {
          return {
            text,
            provider: "openai",
            model: env.OPENAI_MODEL,
            cached: false,
          };
        }
      } catch (e) {
        lastErr = e;
        await new Promise((r) => setTimeout(r, 250 * (i + 1)));
      }
    }
  }

  if (env.ANTHROPIC_API_KEY) {
    for (let i = 0; i < MAX_RETRIES; i++) {
      try {
        const text = await callAnthropic(opts);
        if (text) {
          return {
            text,
            provider: "anthropic",
            model: env.ANTHROPIC_MODEL,
            cached: false,
          };
        }
      } catch (e) {
        lastErr = e;
        await new Promise((r) => setTimeout(r, 250 * (i + 1)));
      }
    }
  }

  if (lastErr && env.NODE_ENV !== "production") {
    // eslint-disable-next-line no-console
    console.warn("[ai] all providers failed, using fallback:", lastErr);
  }

  return {
    text: staticFallback(opts),
    provider: "fallback",
    model: "dealix-static-v1",
    cached: true,
  };
}

export function isAiConfigured(): boolean {
  return Boolean(env.OPENAI_API_KEY || env.ANTHROPIC_API_KEY);
}
