"""Founder GTM Control Room — assembles the daily report and (optionally)
produces the day's drafts from qualified prospects.

    python -m dealix.market_production_os.control_room --date today
    python -m dealix.market_production_os.control_room --produce --print

No external sends ever happen here. ``--produce`` only writes drafts to the
(gitignored) runtime store after running the compliance gate over each.
"""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any

from dealix.market_production_os import store
from dealix.market_production_os.compliance_gate import check_draft
from dealix.market_production_os.draft_factory import produce_daily
from dealix.market_production_os.models import OFFERS
from dealix.market_production_os.prospect_scoring import qualify, score_prospect
from dealix.market_production_os.sending_ramp import RAMP_PHASES

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_OUT = _REPO_ROOT / "reports" / "outreach" / "FOUNDER_GTM_CONTROL_ROOM.md"

# Placeholder sender used for draft generation only (never for sending).
DEFAULT_SENDER: dict[str, str] = {
    "from_name": "Dealix",
    "from_email": "founder@dealix.sa",
    "reply_to": "founder@dealix.sa",
    "physical_address": "Riyadh, Saudi Arabia",
}


def _suppressed() -> set[str]:
    return {r.get("email_sha256", "") for r in store.load("suppression") if r.get("email_sha256")}


def _lines(counter: Counter) -> str:
    if not counter:
        return "- (none)"
    return "\n".join(f"- {key}: {val}" for key, val in counter.most_common())


def produce_and_store(
    *, target: int = 250, sender: dict[str, str] | None = None
) -> list[dict[str, Any]]:
    sender = sender or DEFAULT_SENDER
    prospects = [p for p in store.load("prospects") if qualify(p)]
    drafts = produce_daily(prospects, sender_identity=sender, target=target)
    suppressed = _suppressed()
    for draft in drafts:
        result = check_draft(draft, suppressed_hashes=suppressed)
        draft["compliance_status"] = "pass" if result.allowed else "fail"
        draft["compliance_failures"] = list(result.failures)
    store.write_all("drafts", drafts)
    return drafts


def assemble_report(*, as_of: str | None = None) -> str:
    as_of = as_of or date.today().isoformat()
    prospects = store.load("prospects")
    drafts = store.load("drafts")
    replies = store.load("replies")
    signals = store.load("job_signals")
    partners = store.load("partners")
    post_ideas = store.load("post_ideas")
    suppressed = _suppressed()

    qualified = sum(1 for p in prospects if qualify(p))
    avg_score = (
        round(sum(score_prospect(p).total for p in prospects) / len(prospects), 1)
        if prospects
        else 0
    )
    by_prospect_status = Counter(p.get("status", "researched") for p in prospects)
    by_sector = Counter(p.get("sector", "other") for p in prospects)

    by_touch = Counter(d.get("touch_type", "?") for d in drafts)
    by_offer = Counter(d.get("offer", "?") for d in drafts)
    by_approval = Counter(d.get("approval_status", "pending") for d in drafts)
    by_send = Counter(d.get("send_status", "not_sent") for d in drafts)

    gate_pass = 0
    gate_fail = 0
    fail_reasons: Counter = Counter()
    for draft in drafts:
        result = check_draft(draft, suppressed_hashes=suppressed)
        if result.allowed:
            gate_pass += 1
        else:
            gate_fail += 1
            for failure in result.failures:
                fail_reasons[failure.split(":")[0]] += 1

    by_reply = Counter(r.get("classification", "?") for r in replies)
    by_signal = Counter(s.get("status", "new") for s in signals)
    by_partner_stage = Counter(p.get("stage", "identify") for p in partners)

    ramp_rows = "\n".join(
        f"| {phase} | {label} | {cap} |" for phase, (label, cap) in sorted(RAMP_PHASES.items())
    )
    offer_names = ", ".join(sorted(OFFERS.keys()))

    return f"""# Founder GTM Control Room — غرفة قيادة السوق

**As of / حتى تاريخ:** {as_of}
**Generated by:** `dealix.market_production_os.control_room` (no external sends)

This is the daily go-to-market report. It counts what the system produced and
flags what the founder must decide. See the spec:
[`../../docs/market_production_os/README.md`](../../docs/market_production_os/README.md).

---

## 1. Summary — الملخّص

| Metric | Value |
|---|---|
| Prospects (total) | {len(prospects)} |
| Prospects qualified (score ≥ 60) | {qualified} |
| Avg prospect score | {avg_score} |
| Drafts (total) | {len(drafts)} |
| Drafts passing all gates | {gate_pass} |
| Drafts failing a gate | {gate_fail} |
| Replies logged | {len(replies)} |
| Job signals | {len(signals)} |
| Partners | {len(partners)} |
| Content ideas queued | {len(post_ideas)} |
| Suppressed addresses | {len(suppressed)} |

> **Rule:** 250 drafts/day is allowed. Sends require domain health + ramp cap +
> founder approval. Nothing in this report was sent.

---

## 2. Draft production — إنتاج المسودات

**By touch type:**
{_lines(by_touch)}

**By offer ({offer_names}):**
{_lines(by_offer)}

**Compliance gate:** {gate_pass} pass · {gate_fail} fail
**Top failure reasons:**
{_lines(fail_reasons)}

---

## 3. Approval queue — قائمة الموافقة

**By approval status:**
{_lines(by_approval)}

Founder action: approve / edit / reject the top drafts, then stage an approved
batch within today's ramp cap. See
[`APPROVAL_QUEUE.md`](APPROVAL_QUEUE.md).

---

## 4. Sending — الإرسال

**By send status:**
{_lines(by_send)}

**Ramp phases (max sends/day):**

| Phase | Label | Cap |
|---|---|---|
{ramp_rows}

See [`DELIVERABILITY_REVIEW.md`](DELIVERABILITY_REVIEW.md) and
[`../../docs/outreach/SENDING_RAMP_PLAN_AR.md`](../../docs/outreach/SENDING_RAMP_PLAN_AR.md).

---

## 5. Replies — الردود

{_lines(by_reply)}

See [`REPLY_QUEUE.md`](REPLY_QUEUE.md).

---

## 6. Prospects — العملاء المحتملون

**By status:**
{_lines(by_prospect_status)}

**By sector:**
{_lines(by_sector)}

---

## 7. Signals · Partners · Content

**Job signals by status:**
{_lines(by_signal)}

**Partners by stage:**
{_lines(by_partner_stage)}

**Content ideas queued:** {len(post_ideas)}

---

## 8. Tomorrow — خطة الغد

- Re-rank prospects; refresh personalization to ≥ P2 where possible.
- Approve a batch only if domain health is green and within the ramp cap.
- Convert positive replies to discovery invites; suppress all opt-outs immediately.
- Produce the day's content tied to sector + pain + proof + offer.

---

> Estimated value is not Verified value / القيمة التقديرية ليست قيمة مُتحقَّقة
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Dealix GTM Control Room")
    parser.add_argument("--date", default="today", help="'today' or an ISO date")
    parser.add_argument(
        "--produce", action="store_true", help="produce + store today's drafts first"
    )
    parser.add_argument("--target", type=int, default=250, help="max drafts to produce")
    parser.add_argument("--out", default=str(_DEFAULT_OUT), help="report output path")
    parser.add_argument(
        "--print", dest="do_print", action="store_true", help="print report to stdout"
    )
    args = parser.parse_args(argv)

    as_of = date.today().isoformat() if args.date == "today" else args.date
    if args.produce:
        produced = produce_and_store(target=args.target)
        print(f"produced {len(produced)} drafts")

    report = assemble_report(as_of=as_of)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")
    if args.do_print:
        print(report)
    else:
        print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
