import type { OutreachDraft } from "@/lib/crm/crm";
import { ReviewStatusBadge } from "./ReviewStatusBadge";

export function DraftPreview({ draft }: { draft: OutreachDraft }) {
  return (
    <article className="rounded-2xl border border-neutral-200 bg-white p-5">
      <header className="flex items-center justify-between">
        <div>
          <p className="text-xs uppercase tracking-wide text-neutral-500">
            {draft.channel} · {draft.language} · {draft.createdAt}
          </p>
          <p className="mt-1 text-sm text-neutral-600">Account: {draft.accountId}</p>
        </div>
        <ReviewStatusBadge status={draft.reviewStatus} />
      </header>
      <pre className="mt-4 whitespace-pre-wrap rounded-lg bg-neutral-50 p-4 text-sm leading-relaxed text-neutral-800">
        {draft.body}
      </pre>
      {draft.demo ? (
        <p className="mt-2 text-xs text-yellow-700">DEMO — never sent. Generated by `scripts/generate_outreach_drafts.py --demo`.</p>
      ) : null}
    </article>
  );
}
