"""Golden inventory of every route the FastAPI app registers.

Consolidation work moves routers between modules, collapses duplicated
implementations and removes dead packages. The risk in all of it is the same:
silently dropping a route that something depends on. This module turns the
live routing table into a comparable artifact so that risk becomes a visible,
reviewable diff instead of a production 404.

The golden file is regenerated deliberately, never automatically:

    python3 scripts/generate_route_inventory.py

Every change to ``tests/golden/route_inventory.json`` must appear in its pull
request as an intentional added/removed list. An unexplained diff is a bug.

Shadowed routes
---------------
FastAPI resolves the *first* matching route, so registering the same
``(path, method)`` twice makes the later one unreachable. Those pairs are
recorded separately in the golden file: they are pre-existing defects, and
pinning them means consolidation can only reduce the count, never grow it.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
GOLDEN_PATH = REPO_ROOT / "tests" / "golden" / "route_inventory.json"

# Routes Starlette/FastAPI add on its own behalf. They are real, but they are
# not Dealix surface area and they move with framework upgrades.
FRAMEWORK_PATHS = frozenset(
    {
        "/openapi.json",
        "/docs",
        "/docs/oauth2-redirect",
        "/redoc",
    }
)


def _route_entries(app: Any) -> list[tuple[str, str]]:
    """Return every ``(path, method)`` pair the app serves, duplicates kept."""
    entries: list[tuple[str, str]] = []
    for route in app.routes:
        path = getattr(route, "path", "")
        if not path or path in FRAMEWORK_PATHS:
            continue
        for method in getattr(route, "methods", None) or []:
            # HEAD is auto-added alongside GET; tracking it doubles the file
            # without adding signal.
            if method == "HEAD":
                continue
            entries.append((path, method))
    return entries


def build_inventory(app: Any) -> dict[str, Any]:
    """Build the comparable inventory structure from a live app."""
    entries = _route_entries(app)
    counts = Counter(entries)

    routes: dict[str, list[str]] = {}
    for path, method in sorted(set(entries)):
        routes.setdefault(path, []).append(method)

    shadowed = [
        {"path": path, "method": method, "registrations": count}
        for (path, method), count in sorted(counts.items())
        if count > 1
    ]

    return {
        "_comment": (
            "Generated by scripts/generate_route_inventory.py. "
            "Do not hand-edit. Any diff must be explained in the PR body."
        ),
        "route_count": len(routes),
        "path_method_count": len(set(entries)),
        "shadowed_count": len(shadowed),
        "shadowed": shadowed,
        "routes": routes,
    }


def load_golden() -> dict[str, Any]:
    return json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))


def write_golden(inventory: dict[str, Any]) -> None:
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    GOLDEN_PATH.write_text(
        json.dumps(inventory, indent=2, ensure_ascii=False, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def diff_inventories(
    golden: dict[str, Any], current: dict[str, Any]
) -> tuple[list[str], list[str]]:
    """Return ``(added, removed)`` as human-readable ``METHOD path`` strings."""

    def flatten(inv: dict[str, Any]) -> set[str]:
        return {
            f"{method} {path}"
            for path, methods in inv.get("routes", {}).items()
            for method in methods
        }

    golden_set = flatten(golden)
    current_set = flatten(current)
    return sorted(current_set - golden_set), sorted(golden_set - current_set)
