"""Canonical manifest of the Dealix Startup Operating System.

Single source of truth for: which OS areas exist, their required docs, the
required scripts, tests, workflows, and reports. The scaffold generator creates
these; the verifiers assert they exist. Keep both in sync by editing here.
"""

from __future__ import annotations

# area_key -> (directory, title_en, title_ar, [doc filenames])
OS_AREAS: dict[str, dict] = {
    "company": {
        "dir": "docs/company-os",
        "title": "Company OS",
        "title_ar": "نظام تشغيل الشركة",
        "docs": [
            "00_DEALIX_COMPANY_OS.md",
            "01_EXECUTIVE_STRATEGY.md",
            "02_MARKET_THESIS.md",
            "03_PRODUCT_OPERATING_MODEL.md",
            "04_REVENUE_OPERATING_MODEL.md",
            "05_TRUST_OPERATING_MODEL.md",
            "06_FOUNDER_WEEKLY_CADENCE.md",
            "07_BOARD_STYLE_METRICS.md",
            "08_RISK_REGISTER.md",
            "09_DECISION_LOG.md",
            "10_OPERATING_PRINCIPLES.md",
            "11_90_DAY_COMPANY_ROADMAP.md",
            "12_COMPANY_SCORECARD.md",
            "99_COMPANY_OS_REPORT.md",
        ],
    },
    "product": {
        "dir": "docs/product-os",
        "title": "Product OS",
        "title_ar": "نظام تشغيل المنتج",
        "docs": [
            "00_PRODUCT_OS.md",
            "01_PRODUCT_STRATEGY.md",
            "02_PRODUCT_REQUIREMENTS.md",
            "03_MODULE_MAP.md",
            "04_USER_PERSONAS.md",
            "05_JOBS_TO_BE_DONE.md",
            "06_PRODUCT_ROADMAP.md",
            "07_MVP_SCOPE.md",
            "08_RELEASE_CRITERIA.md",
            "09_PRODUCT_RISK_REGISTER.md",
            "99_PRODUCT_OS_REPORT.md",
        ],
    },
    "site_launch": {
        "dir": "docs/site-launch",
        "title": "Website Launch OS",
        "title_ar": "نظام إطلاق الموقع",
        "docs": [
            "00_SITE_LAUNCH_OS.md",
            "01_PAGE_MAP.md",
            "02_SEO_CHECKLIST.md",
            "03_COPY_DECK_AR_EN.md",
            "04_MANUAL_QA_CHECKLIST.md",
            "05_CONVERSION_PATHS.md",
            "06_LANDING_PAGE_QA.md",
            "99_SITE_LAUNCH_REPORT.md",
        ],
    },
    "commercial_launch": {
        "dir": "docs/commercial-launch",
        "title": "Commercial Launch OS",
        "title_ar": "نظام الإطلاق التجاري",
        "docs": [
            "00_COMMERCIAL_LAUNCH_OS.md",
            "01_FIRST_5_VERTICALS_STRATEGY.md",
            "02_OFFER_LADDER_SAR.md",
            "03_PRICING_AND_PACKAGING.md",
            "04_POSITIONING_AR_EN.md",
            "05_CHANNEL_POLICY.md",
            "06_FOUNDER_DAILY_REVIEW.md",
            "07_COMPLIANCE_AND_SAFETY_GATES.md",
            "08_SALES_MESSAGING_AR_EN.md",
            "09_OBJECTION_HANDLING.md",
            "10_DISCOVERY_CALL_SCRIPT.md",
            "11_PROPOSAL_TEMPLATE_AR_EN.md",
            "12_ONE_PAGE_OFFER_AR_EN.md",
            "13_DELIVERY_OPERATING_SYSTEM.md",
            "14_CLIENT_ONBOARDING.md",
            "15_PILOT_DELIVERY_CHECKLIST.md",
            "16_HANDOVER_SUCCESS_REPORT.md",
            "17_RETENTION_EXPANSION.md",
            "18_EXTERNAL_GO_LIVE_REQUIREMENTS.md",
            "19_GTM_30_DAY_PLAN.md",
            "20_MANUAL_OUTREACH_RAMP.md",
            "21_SUPPRESSION_PROCESS.md",
            "99_FINAL_COMMERCIAL_LAUNCH_REPORT.md",
        ],
    },
    "sales": {
        "dir": "docs/sales-os",
        "title": "Sales OS",
        "title_ar": "نظام المبيعات",
        "docs": [
            "00_SALES_OS.md",
            "01_SALES_PROCESS.md",
            "02_PIPELINE_STAGES.md",
            "03_DISCOVERY_CALL_SCRIPT_AR_EN.md",
            "04_QUALIFICATION_SCORECARD.md",
            "05_PROPOSAL_PROCESS.md",
            "06_CLOSING_PLAYBOOK.md",
            "07_FOLLOW_UP_SEQUENCE.md",
            "08_OBJECTION_LIBRARY.md",
            "09_DEAL_DESK_RULES.md",
            "10_SALES_DASHBOARD_SPEC.md",
            "99_SALES_OS_REPORT.md",
        ],
    },
    "marketing": {
        "dir": "docs/marketing-os",
        "title": "Marketing OS",
        "title_ar": "نظام التسويق",
        "docs": [
            "00_MARKETING_OS.md",
            "01_GTM_STRATEGY.md",
            "02_ICP_AND_SEGMENTATION.md",
            "03_MESSAGING_HIERARCHY.md",
            "04_CHANNEL_STRATEGY.md",
            "05_DEMAND_GEN_PLAN.md",
            "06_CONTENT_ENGINE.md",
            "07_LAUNCH_CAMPAIGN.md",
            "08_REFERRAL_LOOP.md",
            "09_PARTNER_CHANNELS.md",
            "10_MARKETING_METRICS.md",
            "99_MARKETING_OS_REPORT.md",
        ],
    },
    "media_social": {
        "dir": "docs/media-social-os",
        "title": "Media & Social OS",
        "title_ar": "نظام الإعلام والسوشيال",
        "docs": [
            "00_MEDIA_SOCIAL_OS.md",
            "01_BRAND_VOICE.md",
            "02_CONTENT_PILLARS.md",
            "03_30_DAY_CONTENT_CALENDAR.md",
            "04_LINKEDIN_OS.md",
            "05_X_TWITTER_OS.md",
            "06_INSTAGRAM_OS.md",
            "07_TIKTOK_SHORTS_OS.md",
            "08_YOUTUBE_SHORTS_OS.md",
            "09_PRESS_KIT.md",
            "10_ADS_OS.md",
            "11_CREATIVE_BRIEF_LIBRARY.md",
            "12_FOUNDER_PERSONAL_BRAND.md",
            "13_DAILY_MEDIA_ROUTINE.md",
            "14_SOCIAL_METRICS.md",
            "15_ADS_READINESS_GATE.md",
            "99_MEDIA_SOCIAL_READY_REPORT.md",
        ],
    },
    "ads": {
        "dir": "docs/ads-os",
        "title": "Ads OS",
        "title_ar": "نظام الإعلانات",
        "docs": [
            "00_ADS_OS.md",
            "01_ADS_READINESS_GATE.md",
            "02_GOOGLE_SEARCH_PLAN.md",
            "03_LINKEDIN_ADS_PLAN.md",
            "04_META_ADS_PLAN.md",
            "05_UTM_TAXONOMY.md",
            "06_CREATIVE_TEST_PLAN.md",
            "07_ADS_COMPLIANCE_CHECKLIST.md",
            "99_ADS_OS_REPORT.md",
        ],
    },
    "revops": {
        "dir": "docs/revops-os",
        "title": "CRM / RevOps OS",
        "title_ar": "نظام إدارة العلاقات والإيرادات",
        "docs": [
            "00_REVOPS_OS.md",
            "01_CRM_PIPELINE_SCHEMA.md",
            "02_LEAD_INTAKE_PROCESS.md",
            "03_SUPPRESSION_PROCESS.md",
            "04_REPLY_CLASSIFICATION.md",
            "05_PIPELINE_METRICS.md",
            "06_FORECASTING_MODEL.md",
            "07_REVENUE_REVIEW_CADENCE.md",
            "99_REVOPS_OS_REPORT.md",
        ],
    },
    "delivery": {
        "dir": "docs/delivery-os",
        "title": "Delivery / Client Success OS",
        "title_ar": "نظام التسليم ونجاح العملاء",
        "docs": [
            "00_DELIVERY_OS.md",
            "01_DIAGNOSTIC_DELIVERY.md",
            "02_PILOT_DELIVERY.md",
            "03_DEPARTMENT_OS_DELIVERY.md",
            "04_RETAINER_OPERATIONS.md",
            "05_CLIENT_SUCCESS_REPORTING.md",
            "06_HANDOVER_TEMPLATE.md",
            "07_EXPANSION_PLAYBOOK.md",
            "08_SUPPORT_PROCESS.md",
            "09_SLA_AND_ESCALATION.md",
            "99_DELIVERY_READINESS_REPORT.md",
        ],
    },
    "support": {
        "dir": "docs/support-os",
        "title": "Support OS",
        "title_ar": "نظام الدعم",
        "docs": [
            "00_SUPPORT_OS.md",
            "01_SUPPORT_CHANNELS.md",
            "02_TICKET_TRIAGE.md",
            "03_INCIDENT_RESPONSE.md",
            "04_KNOWLEDGE_BASE.md",
            "05_CUSTOMER_FEEDBACK_LOOP.md",
            "99_SUPPORT_OS_REPORT.md",
        ],
    },
    "finance": {
        "dir": "docs/finance-os",
        "title": "Finance OS",
        "title_ar": "النظام المالي",
        "docs": [
            "00_FINANCE_OS.md",
            "01_PRICING_MODEL.md",
            "02_UNIT_ECONOMICS.md",
            "03_CASHFLOW_MODEL.md",
            "04_REVENUE_FORECAST.md",
            "05_EXPENSE_POLICY.md",
            "06_INVOICING_AND_COLLECTIONS.md",
            "07_MONTHLY_FINANCE_REVIEW.md",
            "99_FINANCE_OS_REPORT.md",
        ],
    },
    "legal": {
        "dir": "docs/legal-os",
        "title": "Legal / Compliance OS",
        "title_ar": "النظام القانوني والامتثال",
        "docs": [
            "00_LEGAL_OS.md",
            "01_TERMS_TEMPLATE.md",
            "02_PRIVACY_POLICY_TEMPLATE.md",
            "03_DPA_TEMPLATE.md",
            "04_MSA_TEMPLATE.md",
            "05_SOW_TEMPLATE.md",
            "06_DATA_RETENTION_POLICY.md",
            "07_MARKETING_COMPLIANCE.md",
            "08_PDPL_OPERATING_NOTES.md",
            "99_LEGAL_OS_REPORT.md",
        ],
    },
    "security": {
        "dir": "docs/security-os",
        "title": "Security / Trust OS",
        "title_ar": "نظام الأمان والثقة",
        "docs": [
            "00_SECURITY_TRUST_OS.md",
            "01_SECURITY_BASELINE.md",
            "02_NIST_CSF_MAPPING.md",
            "03_OWASP_TOP_10_MAPPING.md",
            "04_ASVS_CHECKLIST.md",
            "05_SECRET_MANAGEMENT.md",
            "06_ACCESS_CONTROL.md",
            "07_INCIDENT_RESPONSE.md",
            "08_VENDOR_RISK.md",
            "09_SECURITY_EVIDENCE_PACK.md",
            "99_SECURITY_TRUST_REPORT.md",
        ],
    },
    "analytics": {
        "dir": "docs/analytics-os",
        "title": "Analytics OS",
        "title_ar": "نظام التحليلات",
        "docs": [
            "00_ANALYTICS_OS.md",
            "01_EVENT_TAXONOMY.md",
            "02_DASHBOARD_SPEC.md",
            "03_WEEKLY_REPORT_TEMPLATE.md",
            "04_MONTHLY_BOARD_REPORT.md",
            "99_ANALYTICS_READY_REPORT.md",
        ],
    },
    "people": {
        "dir": "docs/people-os",
        "title": "Hiring / People OS",
        "title_ar": "نظام التوظيف والأفراد",
        "docs": [
            "00_PEOPLE_OS.md",
            "01_FIRST_HIRES_PLAN.md",
            "02_ROLE_SCORECARDS.md",
            "03_CONTRACTOR_PLAYBOOK.md",
            "04_INTERVIEW_PROCESS.md",
            "05_ONBOARDING_PROCESS.md",
            "06_PERFORMANCE_CADENCE.md",
            "99_PEOPLE_OS_REPORT.md",
        ],
    },
    "partnerships": {
        "dir": "docs/partnerships-os",
        "title": "Partnerships OS",
        "title_ar": "نظام الشراكات",
        "docs": [
            "00_PARTNERSHIPS_OS.md",
            "01_PARTNER_TYPES.md",
            "02_AGENCY_PARTNER_PLAYBOOK.md",
            "03_TECH_PARTNER_PLAYBOOK.md",
            "04_REFERRAL_PROGRAM.md",
            "05_PARTNER_ENABLEMENT_KIT.md",
            "99_PARTNERSHIPS_OS_REPORT.md",
        ],
    },
    "investor": {
        "dir": "docs/investor-os",
        "title": "Investor / Fundraising OS",
        "title_ar": "نظام المستثمرين",
        "docs": [
            "00_INVESTOR_OS.md",
            "01_INVESTOR_NARRATIVE.md",
            "02_METRICS_FOR_INVESTORS.md",
            "03_DATA_ROOM_INDEX.md",
            "04_PITCH_DECK_OUTLINE.md",
            "05_INVESTOR_QA.md",
            "99_INVESTOR_OS_REPORT.md",
        ],
    },
    "operations": {
        "dir": "docs/operations-os",
        "title": "Operations / Admin OS",
        "title_ar": "نظام العمليات والإدارة",
        "docs": [
            "00_OPERATIONS_OS.md",
            "01_WEEKLY_OPERATING_RHYTHM.md",
            "02_DAILY_COMMAND_CENTER.md",
            "03_VENDOR_REGISTER.md",
            "04_TOOL_STACK_REGISTER.md",
            "05_ACCOUNT_ACCESS_REGISTER.md",
            "06_BACKUP_AND_RECOVERY.md",
            "07_BUSINESS_CONTINUITY.md",
            "99_OPERATIONS_OS_REPORT.md",
        ],
    },
    "go_live": {
        "dir": "docs/go-live",
        "title": "Go-Live OS",
        "title_ar": "نظام الانطلاق الخارجي",
        "docs": [
            "00_EXTERNAL_GO_LIVE_REQUIREMENTS.md",
            "01_DOMAIN_EMAIL_READINESS.md",
            "02_MANUAL_OUTREACH_RAMP.md",
            "03_SUPPRESSION_PROCESS.md",
            "04_PRIVACY_LEGAL_READINESS.md",
            "05_PAYMENT_BOOKING_READINESS.md",
            "06_INCIDENT_AND_COMPLAINT_PROCESS.md",
            "07_PRODUCTION_DEPLOYMENT_CHECKLIST.md",
            "99_GO_LIVE_REPORT.md",
        ],
    },
    "launch_control": {
        "dir": "docs/launch-control",
        "title": "Launch Control Tower",
        "title_ar": "برج التحكم بالإطلاق",
        "docs": [
            "00_FINAL_LAUNCH_CONTROL_TOWER.md",
            "01_LAUNCH_SCORECARD.md",
            "02_GO_NO_GO_MATRIX.md",
            "03_EVIDENCE_PACK.md",
            "04_30_DAY_WAR_ROOM.md",
            "05_DAILY_COMMAND_CENTER.md",
            "06_FAILURE_RESPONSE_PLAYBOOK.md",
            "07_FOUNDER_EXECUTION_CHECKLIST.md",
            "08_STARTUP_OS_MAP.md",
            "99_FINAL_CONTROL_TOWER_REPORT.md",
        ],
    },
}

# Vertical playbooks under commercial-launch/verticals
VERTICAL_DOCS = [
    "01_facilities_management.md",
    "02_contracting_project_controls.md",
    "03_real_estate_property_ops.md",
    "04_legal_professional_services.md",
    "05_consulting_training_b2b.md",
]

REQUIRED_SCRIPTS = [
    "scripts/commercial_generate_400_drafts.py",
    "scripts/commercial_score_drafts.py",
    "scripts/commercial_quality_gate.py",
    "scripts/commercial_compliance_gate.py",
    "scripts/commercial_founder_review_report.py",
    "scripts/commercial_safety_audit.py",
    "scripts/commercial_metrics_summary.py",
    "scripts/commercial_seed_leads_validate.py",
    "scripts/commercial_lead_intake_validate.py",
    "scripts/commercial_launch_readiness.py",
    "scripts/commercial_crm_schema_verify.py",
    "scripts/media_social_calendar_generate.py",
    "scripts/media_social_verify.py",
    "scripts/media_social_metrics_template.py",
    "scripts/site_launch_static_check.py",
    "scripts/api_commercial_static_check.py",
    "scripts/final_secret_and_risk_scan.py",
    "scripts/final_launch_control_verify.py",
    "scripts/startup_os_verify.py",
    "scripts/startup_os_scaffold.py",
]

REQUIRED_TESTS = [
    "tests/test_commercial_generate_400_drafts.py",
    "tests/test_commercial_safety_audit.py",
    "tests/test_commercial_launch_readiness.py",
    "tests/test_commercial_no_external_send.py",
    "tests/test_commercial_quality_gate.py",
    "tests/test_commercial_compliance_gate.py",
    "tests/test_commercial_outputs_schema.py",
    "tests/test_commercial_founder_review_report.py",
    "tests/test_commercial_seed_leads_validate.py",
    "tests/test_media_social_os.py",
    "tests/test_site_launch_static_check.py",
    "tests/test_crm_schema_verify.py",
    "tests/test_api_commercial_static_check.py",
    "tests/test_final_secret_and_risk_scan.py",
    "tests/test_final_launch_control_verify.py",
    "tests/test_startup_os_verify.py",
]

REQUIRED_WORKFLOWS = [
    ".github/workflows/commercial-draft-factory.yml",
    ".github/workflows/media-social-calendar.yml",
    ".github/workflows/site-commercial-verify.yml",
    ".github/workflows/final-launch-control.yml",
    ".github/workflows/startup-os-verify.yml",
]

REQUIRED_CONFIGS = [
    "config/startup_os_offers.json",
    "config/crm_pipeline_schema.json",
    "config/analytics_events.json",
    "config/ad_campaigns_seed.json",
    "data/commercial_seed_leads.example.jsonl",
]
