"""Intelligence: Arabic NLP, ML scoring, sentiment, intent, plus the
comprehensive AI layers stack (see `dealix.intelligence.layers`).
"""

from dealix.intelligence.arabic_nlp import ArabicNLP, normalize_arabic, segment_arabic
from dealix.intelligence.intent import IntentClassifier
from dealix.intelligence.lead_scorer import LeadFeatures, LeadScorer
from dealix.intelligence.sentiment import ArabicSentiment

# Re-export the comprehensive layer stack so callers can do
# `from dealix.intelligence import RAGEngine, NERTagger, ...`.
from dealix.intelligence.layers import (  # noqa: F401
    AnomalyDetector,
    AnomalyResult,
    Chunk,
    Cluster,
    ContentRecommender,
    ConversationMemory,
    EmbeddingModel,
    Entity,
    ExtractiveSummarizer,
    Feedback,
    FeedbackStore,
    ForecastResult,
    Forecaster,
    GatewayResponse,
    KMeansLite,
    Keyphrase,
    KeyphraseExtractor,
    KnowledgeGraph,
    LLMGateway,
    ModerationResult,
    Moderator,
    NERTagger,
    PIIMatch,
    PIIRedactor,
    Pipeline,
    PipelineStep,
    PromptCache,
    RAGEngine,
    RAGResult,
    Recommendation,
    RelationExtractor,
    SafetyClassifier,
    SafetyResult,
    SmartChunker,
    Translator,
    Triple,
    Turn,
    VectorRecord,
    VectorStore,
    ZeroShotClassifier,
    ZeroShotResult,
    embed,
    embed_batch,
)

__all__ = [
    # Legacy
    "ArabicNLP",
    "ArabicSentiment",
    "IntentClassifier",
    "LeadFeatures",
    "LeadScorer",
    "normalize_arabic",
    "segment_arabic",
    # Layer stack
    "AnomalyDetector",
    "AnomalyResult",
    "Chunk",
    "Cluster",
    "ContentRecommender",
    "ConversationMemory",
    "EmbeddingModel",
    "Entity",
    "ExtractiveSummarizer",
    "Feedback",
    "FeedbackStore",
    "ForecastResult",
    "Forecaster",
    "GatewayResponse",
    "KMeansLite",
    "Keyphrase",
    "KeyphraseExtractor",
    "KnowledgeGraph",
    "LLMGateway",
    "ModerationResult",
    "Moderator",
    "NERTagger",
    "PIIMatch",
    "PIIRedactor",
    "Pipeline",
    "PipelineStep",
    "PromptCache",
    "RAGEngine",
    "RAGResult",
    "Recommendation",
    "RelationExtractor",
    "SafetyClassifier",
    "SafetyResult",
    "SmartChunker",
    "Translator",
    "Triple",
    "Turn",
    "VectorRecord",
    "VectorStore",
    "ZeroShotClassifier",
    "ZeroShotResult",
    "embed",
    "embed_batch",
]
