#!/usr/bin/env python3
"""Tenant-isolation audit — scan routers/models for tenant_id discipline.

Two outputs:
  1. docs/reference/TENANT_ISOLATION_AUDIT.md — markdown report
  2. exit-code 0/1 — non-zero if any router queries a tenant-scoped model
     without filtering by tenant_id (best-effort heuristic).

Heuristic limits (documented as such — this is NOT a substitute for a
security review, just a fast smoke check):
  - "tenant_scoped models" = any model whose SQLAlchemy class body
    contains `tenant_id` (read from db/models.py).
  - "tenant-filtered query" = a router that imports that model AND
    references `tenant_id` anywhere in the same file.
  - A router that imports a tenant-scoped model but never mentions
    `tenant_id` is flagged as "needs review".

Read-only. No code changes. Doctrine: this only generates a report —
the human decides what to fix.

Usage:
    python scripts/audit_tenant_isolation.py
    python scripts/audit_tenant_isolation.py --strict   # exit 1 if any flag
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MODELS_PATH = REPO / "db" / "models.py"
ROUTERS_DIR = REPO / "api" / "routers"
OUT_FILE = REPO / "docs" / "reference" / "TENANT_ISOLATION_AUDIT.md"


def _read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


def _tenant_scoped_models() -> set[str]:
    """Return set of model class names whose body mentions tenant_id."""
    text = _read(MODELS_PATH)
    models: set[str] = set()
    # Split by class definitions then check each body for tenant_id
    pattern = re.compile(r"^class\s+(\w+)\s*\(", re.MULTILINE)
    matches = list(pattern.finditer(text))
    for i, m in enumerate(matches):
        name = m.group(1)
        body_start = m.end()
        body_end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[body_start:body_end]
        if re.search(r"\btenant_id\b", body):
            models.add(name)
    return models


def _router_findings(
    router_path: Path, scoped_models: set[str]
) -> tuple[set[str], bool, bool]:
    """Return (imported_scoped_models, has_query, has_tenant_filter)."""
    text = _read(router_path)
    imported: set[str] = set()
    for m in scoped_models:
        if re.search(rf"\b{m}\b", text):
            imported.add(m)
    has_query = bool(
        re.search(r"\.(execute|scalars|first|all|one|one_or_none)\(", text)
        or re.search(r"select\(", text)
    )
    has_tenant_filter = bool(re.search(r"\btenant_id\b", text))
    return imported, has_query, has_tenant_filter


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--strict",
        action="store_true",
        help="exit 1 if any router needs review",
    )
    args = ap.parse_args()

    scoped = _tenant_scoped_models()
    if not scoped:
        print("WARN: no tenant-scoped models detected — is db/models.py present?")
        return 0

    rows: list[tuple[str, str, str, str]] = []
    needs_review_count = 0
    for path in sorted(ROUTERS_DIR.glob("*.py")):
        if path.stem == "__init__":
            continue
        imported, has_query, has_filter = _router_findings(path, scoped)
        if not imported:
            continue  # router doesn't touch tenant-scoped models
        imports_str = ", ".join(sorted(imported))
        if not has_query:
            verdict = "ℹ️  imports-only"
        elif has_filter:
            verdict = "✅ tenant_id present"
        else:
            verdict = "⚠️  needs review"
            needs_review_count += 1
        rows.append((path.stem, imports_str, "yes" if has_query else "no", verdict))

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    out: list[str] = []
    out.append("# Tenant Isolation Audit")
    out.append("")
    out.append(
        f"> Auto-generated by `scripts/audit_tenant_isolation.py`. "
        f"Scoped models: **{len(scoped)}**. Routers touching them: "
        f"**{len(rows)}**. Need review: **{needs_review_count}**."
    )
    out.append("")
    out.append("## Heuristic limits")
    out.append("")
    out.append(
        "- A router that imports a `tenant_id`-bearing model AND issues a "
        "query (select/execute/scalars/first/all/one) AND never mentions "
        "`tenant_id` in its source is flagged as **needs review**."
    )
    out.append(
        "- A router that imports the model but never queries (e.g. uses the "
        "class for type hints only) is marked **imports-only** — almost "
        "always safe."
    )
    out.append(
        "- Pydantic models, dataclasses, and JSON dicts named tenant_id but "
        "not in `db/models.py` are NOT scoped — this scan looks only at the "
        "SQLAlchemy classes there."
    )
    out.append(
        "- This is a smoke check, not a security review. A `needs review` "
        "flag means a human must confirm the query is correctly scoped "
        "(via session.execute(stmt.where(Model.tenant_id == ...)) or via a "
        "tenant-aware base session)."
    )
    out.append("")
    out.append(f"## Scoped models ({len(scoped)})")
    out.append("")
    for m in sorted(scoped):
        out.append(f"- `{m}`")
    out.append("")
    out.append("## Findings")
    out.append("")
    if not rows:
        out.append("_No routers import any of the scoped models._")
    else:
        out.append("| Router | Models imported | Queries? | Verdict |")
        out.append("|--------|-----------------|----------|---------|")
        for stem, imports, hq, verdict in rows:
            out.append(f"| `{stem}` | {imports} | {hq} | {verdict} |")
    out.append("")
    OUT_FILE.write_text("\n".join(out) + "\n", encoding="utf-8")

    print(
        f"OK: wrote {OUT_FILE.relative_to(REPO)} · "
        f"{len(rows)} routers touch scoped models · "
        f"{needs_review_count} need review"
    )
    if args.strict and needs_review_count:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
