"""Generate the founder's daily brief from private_ops state.

Pure read-only. Writes to private_ops/founder/ceo_daily_brief.md by default
(or stdout if --output is omitted). Never sends, never charges, never posts.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _private_ops_runtime import (  # noqa: E402
    ledger_path,
    parse_args,
    read_csv,
    section,
    today_iso,
    write_or_print,
)


def main() -> int:
    args = parse_args("generate_ceo_daily_brief")
    po = args.private_ops

    decisions = ledger_path(po, "founder", "decision_log.csv")
    approvals = ledger_path(po, "approvals", "approval_queue.csv")
    delegation = ledger_path(po, "founder", "delegation_queue.csv")
    incidents = ledger_path(po, "trust", "incidents.csv")
    revenue_md = ledger_path(po, "finance", "revenue_forecast.md")

    missing = [p for p in (decisions, approvals, delegation) if not p.exists()]
    if missing and args.strict:
        for p in missing:
            print(f"[strict] missing ledger: {p}", file=sys.stderr)
        return 1

    _, dec_rows = read_csv(decisions)
    _, app_rows = read_csv(approvals)
    _, del_rows = read_csv(delegation)
    _, inc_rows = read_csv(incidents)

    open_approvals = [r for r in app_rows if (r.get("status") or "").lower() in
                      {"", "open", "pending", "awaiting_founder"}]
    open_delegations = [r for r in del_rows if (r.get("status") or "").lower() in
                        {"", "open", "in_progress"}]
    open_incidents = [r for r in inc_rows if (r.get("status") or "").lower() in
                      {"", "open", "investigating"}]
    last_decisions = list(reversed(dec_rows))[:5]

    parts = [f"# CEO Daily Brief — {today_iso()}\n"]
    parts.append("Source: private_ops (read-only). Generated by scripts/generate_ceo_daily_brief.py.\n")

    parts.append(section(
        f"Approvals awaiting founder ({len(open_approvals)})",
        (f"{r.get('id', '?')} — {r.get('summary', r.get('action', ''))}"
         for r in open_approvals[:10]),
    ))
    parts.append(section(
        f"Open delegations ({len(open_delegations)})",
        (f"{r.get('id', '?')} → {r.get('owner', '?')}: {r.get('task', '')}"
         for r in open_delegations[:10]),
    ))
    parts.append(section(
        f"Open trust incidents ({len(open_incidents)})",
        (f"{r.get('id', '?')} — {r.get('severity', '?')} — {r.get('summary', '')}"
         for r in open_incidents[:10]),
    ))
    parts.append(section(
        "Last 5 founder decisions",
        (f"{r.get('date', '?')} — {r.get('decision', '')}" for r in last_decisions),
    ))
    if revenue_md.exists():
        parts.append("## Revenue forecast snapshot\n\n```\n"
                     + revenue_md.read_text(encoding="utf-8")[:2000]
                     + "\n```\n")
    else:
        parts.append("## Revenue forecast snapshot\n\n(no forecast yet — run `make revenue-forecast`)\n")

    write_or_print("\n".join(parts), args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
