"""Generate the canonical Dealix frontend route inventory.

Scans:
  - landing/*.html   (static marketing surface)
  - apps/web/app/**/page.tsx  (founder Next.js console)

Writes:
  - docs/frontend/FRONTEND_ROUTE_INVENTORY.generated.md

The hand-curated inventory (FRONTEND_ROUTE_INVENTORY.md) provides ownership,
purpose, CTA, and data sources. This script produces the *actual file → route*
mapping so the two can be compared.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LANDING = REPO_ROOT / "landing"
WEB_APP = REPO_ROOT / "apps" / "web" / "app"
OUT = REPO_ROOT / "docs" / "frontend" / "FRONTEND_ROUTE_INVENTORY.generated.md"


def _route_from_page(page: Path) -> str:
    rel = page.parent.relative_to(WEB_APP)
    parts = [p for p in rel.parts if p not in (".",)]
    if not parts:
        return "/"
    return "/" + "/".join(parts)


def collect() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    if LANDING.exists():
        for html in sorted(LANDING.glob("*.html")):
            rows.append({"source": "landing", "route": "/" + html.name, "file": str(html.relative_to(REPO_ROOT))})
    if WEB_APP.exists():
        for page in sorted(WEB_APP.rglob("page.tsx")):
            rows.append({"source": "apps/web", "route": _route_from_page(page), "file": str(page.relative_to(REPO_ROOT))})
    return rows


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    rows = collect()
    lines = [
        "# Frontend Route Inventory (generated)",
        "",
        "Generated by `scripts/generate_frontend_route_inventory.py`. Do not edit by hand.",
        "Compare against `FRONTEND_ROUTE_INVENTORY.md` for ownership and purpose.",
        "",
        f"Total routes: **{len(rows)}** "
        f"(landing: {sum(1 for r in rows if r['source'] == 'landing')}, "
        f"apps/web: {sum(1 for r in rows if r['source'] == 'apps/web')})",
        "",
        "| Source | Route | File |",
        "|---|---|---|",
    ]
    for row in rows:
        lines.append(f"| {row['source']} | `{row['route']}` | `{row['file']}` |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"PASS: wrote {OUT.relative_to(REPO_ROOT)} ({len(rows)} routes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
