import { loadAccounts, summarize } from "@/lib/crm/crm";

export const metadata = { title: "CRM reports — Dealix" };
export const dynamic = "force-static";

export default function CrmReportsPage() {
  const accounts = loadAccounts();
  const s = summarize(accounts);

  return (
    <main className="mx-auto max-w-4xl px-6 py-12">
      <h1 className="text-2xl font-semibold tracking-tight">CRM reports</h1>
      <p className="mt-2 text-sm text-neutral-600">Generated by founder operator scripts.</p>

      <section className="mt-8 rounded-2xl border border-neutral-200 p-6">
        <h2 className="text-lg font-semibold">Pipeline snapshot</h2>
        <ul className="mt-3 space-y-1 text-sm">
          <li>Accounts: <b>{s.count}</b></li>
          <li>Avg score: <b>{s.avgScore}</b></li>
          <li>Pipeline MRR: <b>{s.pipelineMrr.toLocaleString()} SAR</b></li>
          <li>Pipeline setup: <b>{s.pipelineSetup.toLocaleString()} SAR</b></li>
        </ul>
      </section>

      <section className="mt-6 rounded-2xl border border-neutral-200 p-6">
        <h2 className="text-lg font-semibold">By stage</h2>
        <ul className="mt-3 space-y-1 text-sm">
          {s.stages.map((row) => (
            <li key={row.stage}>{row.stage}: <b>{row.count}</b></li>
          ))}
        </ul>
      </section>

      <section className="mt-6 rounded-2xl border border-neutral-200 p-6">
        <h2 className="text-lg font-semibold">Generate reports</h2>
        <pre className="mt-3 overflow-x-auto rounded-lg bg-neutral-900 p-4 text-xs text-neutral-100">
{`python3 scripts/generate_pipeline_report.py
python3 scripts/generate_daily_ceo_brief.py
python3 scripts/generate_weekly_operating_review.py
python3 scripts/generate_monthly_client_review.py`}
        </pre>
      </section>
    </main>
  );
}
